### PR TITLE
[RFR]: AutocompleteArrayInput and jest snapshot testing

### PR DESCRIPTION
**Pull request by tkvw**
Follow #1410 

Created a rudimentary implementation of `SelectArrayInput`, before going forward I like to know what direction you want to go. This implementation just adds a `startAdornment` to the (fixed) `AutocompleteInput` (that's why the AutocompleteInput changes are in the PR as well). It supports adding while typing, delete using backspace, and a click handler. It has no additional external dependencies. 

- [X] Create component
- [X] Add tests
- [X] Add docs

### CODE REVIEW

**Comment by fzaninotto** [comment]
IMO, this is a great start, but in a direction different to what we want. 

We want to get a `SelectArrayInput` fast, and that means without autocomplete. Maybe we'll introduce an `AutocompleteArrayInput` in the future, but the only thing that we want to implement before releasing 2.0, is a simple `SelectArrayInput`. Your PR makes one component more complex, we're looking for many, simpler components.

**Comment by tkvw** [comment]
Fine, by me. It's actually just a composition of `AutocompleteInput` and a startadornment, so not very complicated. Like I said, it's based on the PR https://github.com/marmelab/admin-on-rest/pull/1410 of `Autocomplete` which I think is still broken. So this implementation is actually much smaller than it looks. 

I just wanted to mention; thanks for all the work and effort you and your team put into the project.

**Comment by fzaninotto** [comment]
The simple `<SelectArrayInput>` was implemented in #1495. This PR should therefore be repurposed to create an `<AutocompleteArrayInput>`.

**Comment by tkvw** [comment]
Changed it to `<AutocompleteArrayInput>`

**Comment by tkvw** [comment]
Rebased and added jest snapshot testing: 

Snapshot testing: 
* Gives better understanding of what's rendered
* Makes testing easier
* Snapshots should be versioned and verified
* Only snapshot `shallow`, not `mount`

See: 

* https://facebook.github.io/jest/docs/en/snapshot-testing.html
* https://hackernoon.com/testing-react-components-with-jest-and-enzyme-41d592c174f

**Comment by fzaninotto** [comment]
We're very aware of snapshot testing, and we don't want it. It tends to test too much details, and breaks too often. Please use more atomic unit tests instead.

**Comment by fzaninotto** [comment]
This PR was closed by GitHub when I renamed the repository from "admin-on-rest" to "react-admin", and the `next` branch `master`.

Would you mind reopening a new one with the same changes?

**Pull request closed without merging**
