### PR TITLE
Fix/set-correct-label-for-select-array-input

### PR DESCRIPTION
**Pull request by sebastianbuechler**
After receiving an answer from the MUI team (https://github.com/mui/material-ui/issues/36164) I open the fix for the original issue in #8465 here. For better testing, I added the two remaining variants of the `SelectArrayInput` into the storybook [here](https://react-admin-storybook-qrjp3wcs9-marmelab.vercel.app/?path=/story/ra-ui-materialui-input-selectarrayinput--basic).

### CODE REVIEW

**Review by slax57 — APPROVED** [review]
Thanks!

**Comment by sebastianbuechler** [comment]
@slax57 Thank you, really enjoy working with react-admin!

**Comment by WiXSL** [comment]
This is related to #8498

**Comment by slax57** [comment]
You're 100% right @WiXSL , thanks for pointing that out! :slightly_smiling_face:

**Pull request merged**
