### PR TITLE
Accept object as valid parameter for toolbar

### PR DESCRIPTION
**Pull request by pnthang01**
This input should accept object as valid parameter for toolbar for advance custom.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Can you explain the use case and document the new option? 

Also, this is technically a new feature, so it should be PRed against the `next` branch

**Comment by pnthang01** [comment]
Hi, base on this Quill's documentation for toolbar, it can custom container and handlers(object). And I need to to use this custom handlers but your component only accepts bool or array as param.
https://quilljs.com/docs/modules/toolbar/
Thanks

**Comment by fzaninotto** [comment]
OK, still waiting for the documentation and the rebase against `next`

**Comment by fzaninotto** [comment]
Bump

**Comment by fzaninotto** [comment]
No news for too long, closing

**Pull request closed without merging**
