### PR TITLE
Fix IE11 layout problem caused by `flex-basis: auto`

### PR DESCRIPTION
**Pull request by phacks**
As mentioned in #2676, IE11 suffers from several layout problems where the user would have to horizontally scroll to see all content and/or images would get absurdly distorted.

https://github.com/philipwalton/flexbugs/issues/170 seems to show that IE11 shows inconsistency when using `flex-basis: auto` (or the shorthand version: `flex: X Y auto`).

I tried changing `auto` by `0px` in such statements, and it looks like it fixed many of those layout problems in the demo app:

| 🙁Before (IE11) | 🙂After (IE11) |
|---|---|
| image | image |
| image | image |
| image | image |

I also had to remove the `display: flex` and `flex-wrap: wrap` on `SegmentsField` because IE11 [has](https://stackoverflow.com/questions/31022747/flexbox-ie11-flex-wrap-wrap-does-not-wrap-images-codepen-inside) [many](https://stackoverflow.com/questions/35111090/text-in-a-flex-container-doesnt-wrap-in-ie11/35113633) [problems](https://github.com/philipwalton/flexbugs/issues/179) with `flex-wrap: wrap`. The wrapping still works (Chrome + IE11) though.

Navigating the demo app on Chrome showed me no visual regression, and `<Aside />` components (for which the `flex-basis: auto` were introduced) still work as expected:

image
image

### CODE REVIEW

**Comment by fzaninotto** [comment]
This needs thorough testing across multiple browsers

**Comment by phacks** [comment]
@fzaninotto of course — how would you like me to proceed?

**Comment by phacks** [comment]
@fzaninotto Hi! Did you have time to run some browser testing on this issue?

Let me know if I can be of any help 🙂

**Comment by phacks** [comment]
@fzaninotto Hi! Do you think you will have some time to test this PR soon? cc @Kmaschta 

Thanks!

**Comment by Kmaschta** [comment]
I booked 15min tomorrow to test that branch locally

**Comment by Kmaschta** [comment]
I tested these layouts on several browsers (latest version), it is OK for me :+1: 

Here are the screenshots for each of them:

<details>

<summary>Google Chrome (Windows)</summary>

image

image

image

</details>

<details>

<summary>Internet Explorer 11 (Windows)</summary>

image

image

image

</details>

<details>

<summary>Mozilla Firefox (Windows)</summary>

image

image

image

</details>

<details>

<summary>Safari 12 (MacOS)</summary>

image

image

image

</details>

<details>

<summary>Edge (Windows)</summary>

image

image

image

</details>

<details>

<summary>Opera (Windows)</summary>

image

image

image

</details>

**Comment by phacks** [comment]
@Kmaschta thanks for the review! Do you think this PR can make it for the `2.7.2` / `2.8.0` milestones?

**Comment by fzaninotto** [comment]
Not good: I see an additional scrollbar at the bottom of the Comment List in the simple demo (Chrome, Ubuntu):

image

and at the bottom of the Posters list in the demo (Safari, macOS)

image

and on Windows as well:

image

So I can't merge this PR as is.

**Comment by phacks** [comment]
@fzaninotto Oops, I can work on it next week, will keep you updated!

**Comment by phacks** [comment]
@batbyR found another, cleaner solution that get rid of the superfluous scrollbars at the bottom! You may have a look over at #2969

**Pull request closed without merging**
