### PR TITLE
Add up and down buttons to allow reordering

### PR DESCRIPTION
**Pull request by ibobo**
As requested in #5584 here's my PR for the up and down arrows to allow reordering. Sorry for the delay!

I'm open for discussion.

### CODE REVIEW

**Review by djhi — COMMENTED** [review]
Looks good so far :+1: Would you mind adding a screencast of the result in the PR description? Also, we need some tests for this feature :)

**Comment by audunhalland** [comment]
The momentum slowed down a little? Should someone take over this PR?

**Comment by djhi** [comment]
@ibobo Thanks for the PR. Can you please add tests and target the `next` branch as it is a new feature?

**Comment by djhi** [comment]
@ibobo I just checked out your PR locally and I'm afraid we won't merge it in its current state. This is what it looks like now:

image

First, the button should be inside `span` or `div` to avoid the ugly hover effect. We suggest you put the buttons under the item label (which is an index by default).

**Comment by fzaninotto** [comment]
Superseded by #6433

**Pull request closed without merging**
