### PR TITLE
[BC Break] [RFR] Upgrade dependencies

### LINKED ISSUE #1999: Deprecation of react-router-redux
React-router-redux is deprecated as can be seen here:
https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

Any plans on finding an alternative?

### PR DESCRIPTION
**Pull request by fzaninotto**
The goal of this PR is to prepare the transition to react hooks.

- [x] Upgrade `react` et `react-dom` to 18.6
- [x] Upgrade react-redux to 7.1.0-alpha.1
- [x] As a consequence, upgrade redux-form to 8.2
- [x] As a consequence, change `react-router-redux` to `connected-react-router` (closes #1999)
- [x] As a consequence, rename the `<Resource context>` prop to `<Resource intent>` (because react-redux now injects a `context` prop)
- [x] Fix tests and type warnings
- [x] Bootstrap Migration guide
- [x] Upgrade a few dev dependencies (`jest`, `enzyme`, `rimraf`)
- [x] ~~Upgrade redux-saga~~ reverted that one, it's too much work for now 
- [x] Fix TabbedForm loses values when navigating in tabs
- [x] Fix CloneButton

### CODE REVIEW

**Comment by fzaninotto** [comment]
There are still warnings in the console when running the simple and demo examples, but it's working. I'm trying to get rid of them.

**Comment by fzaninotto** [comment]
the CloneButton fails because it uses location.state, which is currently not supported by `connected-react-router`... (se https://github.com/supasate/connected-react-router/issues/301)

**Comment by znk** [comment]
Hello @fzaninotto, in your knowledge, is it possible to try this branch' sub-packages with a package manager? e.g `yarn add marmelab/react-admin#refs/heads/upgrae-dependencies/<path-to-sub-package>`

**Comment by fzaninotto** [comment]
@znk This is not released yet - not even merged. We don't encourage using unpublished code.

**Pull request merged**
