### PR TITLE
[RFR] Support for inline fragments for GraphQL Interfaces

### PR DESCRIPTION
**Pull request by MichielDeMey**
This PR adds improved support for GraphQL `Interface` types.

For example if you have the following schema:
```graphql
interface Device {
  prop1
}

type MotionSensor implements Device {
  prop2
}

type TemperatureSensor implements Device {
  prop3
}
```

It will now generate the correct inline fragments for the interface when building the GraphQL query.
```graphql
devices {
  ... on MotionSensor {
    prop1
    prop2
  }
  ... on TemperatureSensor {
    prop1
    prop3
  }
  prop1
}
```

Allowing you to get `prop2` and `prop3` from the resource in react-admin.

```jsx
<TextField source="prop1" />
<TextField source="prop2" />
<TextField source="prop3" />
```

**Note: Requires https://github.com/marmelab/react-admin/pull/3692 and https://github.com/marmelab/react-admin/pull/3712 to be merged**

### CODE REVIEW

**Comment by fzaninotto** [comment]
New features should be PRed against the `next` branch, can you please rebase?

**Comment by djhi** [comment]
It needs rebase because #3712 has been merged

**Comment by djhi** [comment]
@fzaninotto I think this can be merged on master. It's not really a new feature but a better support for existing things in GQL

**Comment by fzaninotto** [comment]
Fine, let's merge it on master once it's rebased.

**Comment by MichielDeMey** [comment]
PR rebased to `master` now. 👍

**Comment by fzaninotto** [comment]
but tests fail...

**Comment by MichielDeMey** [comment]
Tests have been fixed :)

**Comment by djhi** [comment]
Thanks!

**Pull request merged**
