### PR TITLE
Extended downloadCSV helper with type paramater

### PR DESCRIPTION
**Pull request by ValentinnDimitroff**
Recently I needed to change the output encoding (text/csv;charset=utf-8) of the csv file. I had to reimplement it at my side because currently there is no way to  plug in at the type sport and customize the output. 

That's why I am proposing this extended parameter with default value if nothing is passed in.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Shouldn't `text/csv;charset=utf-8` be the default mime type? After all, the output always uses UTF-8, right?

**Comment by ValentinnDimitroff** [comment]
Actually I also think it is better to be the default mime type. In my case it appears it was not the default behaviour because I had unreadble cyrilic symbols in the exported csv file. After the change it all started working correctly. 

I just wanted to keep everything as it was but if you don't mind I can replace the parameter's default value and update the PR?

**Comment by fzaninotto** [comment]
yes, please!

**Comment by fzaninotto** [comment]
I didn't make myself clear enough: I think we don't need to make the type customizable is we modify it to always be utf-8. So you could just make it a bug fix instead of an enhancement.

**Comment by ValentinnDimitroff** [comment]
Yeah, sounds as the most sensible solution. Didn't catch your point the first time - I rebased to master now as it is just a bug fix.

**Review by djhi — APPROVED** [review]

**Pull request merged**
