### PR TITLE
Convert ra-data-graphql to TypeScript

### PR DESCRIPTION
**Pull request by CarsonF**

### CODE REVIEW

**Comment by fzaninotto** [comment]
since you're reviewing the code of this package made for 2.x, please also change the dataProvider to an object. Using a function with a method argument is deprecated. 

See https://marmelab.com/react-admin/DataProviders.html#writing-your-own-data-provider for details. 

Also, to minimize the risks of a breaking change, please open the pull request on `next` rather than `master`. We only publish bug fixes in the 3.1.x releases.

**Comment by CarsonF** [comment]
I can do that. I was thinking about it anyways I just was going to keep it separate.

That directly affects the other packages that depend on this one. They are expecting the legacy provider not the new one. 

Maybe those could be upgraded to TS first?

**Comment by fzaninotto** [comment]
Sure

**Comment by fzaninotto** [comment]
Any updates?

**Comment by hgiasac** [comment]
Due to long inactivity. I update this PR to new one, with dataProvider update #4909. @fzaninotto  Can you review it? Thanks

**Comment by fzaninotto** [comment]
Superseded by #4909

**Pull request closed without merging**
