### PR TITLE
Update .eslintrc

### PR DESCRIPTION
**Pull request by rajankouzina**

### CODE REVIEW

**Review by djhi — COMMENTED** [review]
Can you please explain why we merge this ?

**Comment by rajankouzina** [comment]
While creating a clone, I was getting delete cr prettier/prettier.
https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-delete-cr-prettier-prettie
This helped me

**Comment by fzaninotto** [comment]
So you mean you're on Windows?

**Comment by rajankouzina** [comment]
I have ubuntu and windows. I was facing it in both OS

**Pull request closed without merging**
