### PR TITLE
RA-OSS-12 - InputHelperText - String error messages are not translated

### PR DESCRIPTION
**Pull request by gitstart**
Here is the GitStart Ticket for this pull request: [RA-OSS-12](https://developers.gitstart.com/client/reactadmin-oss/ticket/RA-OSS-12)

- Please mark your PR as "ready for review" when you have completed all requirements.
- Please ensure that your PR is reviewed by at least 2 people after you have completed it.
- Comments for review or requested changes from the upstream client will be notified to you by email and will also show on the [ticket page](https://developers.gitstart.com/client/reactadmin-oss/ticket/RA-OSS-12).
- After the PR is merged on the upstream, please merge this PR.
- If there exist merge conflicts on your current PR and you have to close the PR instead of merging it, please go to the [ticket page](https://developers.gitstart.com/client/reactadmin-oss/ticket/RA-OSS-12) to manually finish the task that is related to this PR.

Happy hacking! 🎉

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

---

Fixes https://github.com/marmelab/react-admin/issues/9084
Potential duplicate of https://github.com/marmelab/react-admin/pull/9090

### CODE REVIEW

**Review by djhi — COMMENTED** [review]
Thanks for the PR. This is not the correct fix though, as explained in #9090

**Comment by gitstart** [comment]
> Thanks for the PR. This is not the correct fix though, as explained in #9090

@djhi we have updated the test with the translated messages

**Comment by jm-masteos** [comment]
Hi guys planning on merging this any soon ? We are really waiting for that little update. Any idea when it will be released ?

**Comment by slax57** [comment]
> @djhi we have updated the test with the translated messages

@gitstart No, the test is correct and should not be changed. It is the code that needs to be fixed.

Actually the issue is deeper that simply a missing call to `translate()`, as we need to figure out a way not to call `translate()` twice when using `SimpleForm`. Otherwise we get the "Missing translation for key" warnings which we want to avoid.

> Hi guys planning on merging this any soon ? We are really waiting for that little update. Any idea when it will be released ?

@jm-masteos I don't know how to fix this yet, so can't provide any ETA for now. Your feedback has been taken into account however, and we'll try to prioritize this issue.

**Comment by jm-masteos** [comment]
@slax57 Hi I have an idea that could guide you in finding the best fix.

Try to implement a test in `Form.spec.tsx` to ensure that yup error messages are translated.

`
      it('should translate the error messages from react-hook-form resolvers', async () => {
        const onSubmit = jest.fn();
        const schema = yup
            .object({
                title: yup.string().required('this.should.be.translated'),
                number: yup
                    .number()
                    .positive()
                    .integer()
                    .required('this.should.be.translated'),
            })
            .required();

        render(
            <CoreAdminContext
                i18nProvider={{
                    translate,
                    changeLocale: () => Promise.resolve(),
                    getLocale: () => 'en',
                }}
            >
                <Form
                    onSubmit={onSubmit}
                    resolver={yupResolver(schema, undefined, { mode: 'sync' })}
                >
                    <Input source="title" />
                    <Input
                        source="number"
                        aria-label="Number"
                        defaultValue={-10}
                    />
                    <button type="submit">Submit</button>
                </Form>
            </CoreAdminContext>
        );

        fireEvent.click(screen.getByText('Submit'));

        await waitFor(() => {
            screen.getByText('translated');
        });
        await waitFor(() => {
            screen.getByText('Translated');
        });
        screen.getByText('number must be a positive number');
    });
            `

**Comment by fzaninotto** [comment]
As seen in #9084, this isn't the right fix, so I'm closing this PR.

**Pull request closed without merging**
