### PR TITLE
SaveButton renders disabled if Form is pristine.

### PR DESCRIPTION
**Pull request by WiXSL**
Implements #4733

### CODE REVIEW

**Comment by fzaninotto** [comment]
This is technically a new feature, please PR against `next` rather than `master`.

**Comment by kopax** [comment]
Excellent. I wonder how I could have missed the SaveButton. Anyway, I would not have added such correct test to the application. Good job thank you really much @WiXSL!

**Comment by WiXSL** [comment]
@kopax The `saving` prop is already handling that issue in the `SaveButton` component.

**Comment by fzaninotto** [comment]
Thanks!

**Comment by kopax** [comment]
Hi guys, just wondering now that 3.6.0 is out, I am testing it in my back office app, and this is what I got:

image

This is what I have in my `node_modules`:

```bash
$ cat node_modules/react-admin/package.json | grep version
  "version": "3.6.0"
$  cat node_modules/ra-core/package.json | grep version
  "version": "3.6.0"
$ cat node_modules/ra-ui-materialui/package.json | grep version
  "version": "3.6.0"
```

Was this really shipped in 3.6.0?  What am I missing?

**Comment by johnlepikhin** [comment]
Is there a way to disable this feature for some form? It breaks Clone behaviour. User just can't save exactly the same object.

**Pull request merged**
