### PR TITLE
Sanitize emptyText, enableGetChoices @ SAI

### PR DESCRIPTION
**Pull request by ZachSelindh**
When using a SelectArrayInput as a child of a ReferenceArrayInput, DOM errors will be thrown for the props "emptyText" and "enableGetChoices". This commit sanitizes those props before they are passed to the FormControl component, which triggers the DOM error.

### CODE REVIEW

**Comment by fzaninotto** [comment]
I can't replicate the problem of DOM warnings. Can you please point to a CodeSandbox replicating the issue?

**Comment by ZachSelindh** [comment]
Sure! Here's a fork that shows the issue using a new "Subtitle" input with a ReferenceArrayInput and SelectArrayInput.

https://codesandbox.io/s/damp-river-jqr32?file=/src/posts/PostCreate.tsx

**Review by WiXSL — APPROVED** [review]

**Comment by WiXSL** [comment]
Looks ok!

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
