### PR TITLE
Add docs translation for new indonesian translation

### PR DESCRIPTION
**Pull request by danangekal**
Hi Creators, Mainteners & Contributors,

I added document translation to rebuild a new Indonesian translation. I rebuilt with a typescript & fixed a missing type for the translated message 'ra.navigation.skip_nav'. I hope to merge & publish them.

Thanks.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Hi, and thanks for your patch.

I'd prefer if you updated the existing indonesian package. Did you try submitting a PR to their repository?

**Comment by danangekal** [comment]
Hi @fzaninotto,
I have submitted for an update but there is no response. Because I needed to be able to solve problems with the application that I made, I finally decided to publish it myself. This is my submission link [Enhancement convert to typescript with update translation indonesian](https://github.com/ronadi/ra-language-indonesian/pull/1)

**Comment by fzaninotto** [comment]
@danangekal In that case, let's wait a bit (let's say another week) for the initial package to be updated. It it's not, please update this PR to *replace* the link with the one of your repo. I prefer to have only one (maintained) translation per locale.

**Comment by fzaninotto** [comment]
Hi, would you mind updating your PR to replace the outdated link with yours?

**Comment by danangekal** [comment]
Hi, I've updated the outdated Indonesian translation link. Thank you for your attention @fzaninotto.

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
