### PR TITLE
[Docs]: Improve buttons sanitation explanation.

### PR DESCRIPTION
**Pull request by WiXSL**
Because of #4574

### CODE REVIEW

**Comment by fzaninotto** [comment]
This conflicts with #4544 (already in master). Let me merge `master` into `next` and you'll change what needs to be changed.

**Comment by fzaninotto** [comment]
Done, please rebase

**Comment by WiXSL** [comment]
Done.

**Comment by fzaninotto** [comment]
I don't understand, the previous code snippet already took care of sanitizing the extra props.

**Comment by Kmaschta** [comment]
Since we fixed the CreateButton props sanitation, and this Create and Edit views documentation already have a lot of tips and examples, I'm in favor of removing this tip.
It is not the purpose of React Admin to explain how Material UI components work ?

**Comment by WiXSL** [comment]
Actually the idea of #4574 was to remove #4544, Buy I didnt want to remove somebody elses work, so I improve it to a common use case  that has the same problem. A custom button could be created out of any librarte I justo use material-ui as an example.

**Comment by WiXSL** [comment]
They are not white spaces, they are zero width unicode characters (in this case \u200B).
I asume someone add them accidentally.
But I'll reverted back if you want, no problems.

Please confirm about this.

**Comment by fzaninotto** [comment]
You're right! How did you detect those? Some of us may have a bad setting in their IDE.

**Comment by WiXSL** [comment]
I'm using a plugin for JetBrains IDEs.

https://plugins.jetbrains.com/plugin/7448-zero-width-characters-locator

**Comment by fzaninotto** [comment]
Nice. I found this equivalent plugin for VSCode: https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins

**Comment by WiXSL** [comment]
Oh, I'll take note of that. Thanks.

**Pull request merged**
