### PR TITLE
Fix typos in comments and string literals

### PR DESCRIPTION
**Pull request by WiXSL**

### CODE REVIEW

**Comment by WiXSL** [comment]
Ready for review

**Comment by WiXSL** [comment]
Ready for review

**Comment by WiXSL** [comment]
Ready for review

**Comment by WiXSL** [comment]
Ready for review

**Review by djhi — CHANGES_REQUESTED** [review]
Thanks! Can you revert the changes on tsconfig.json please?

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Tremendous work! 😍 

Thanks a lot, this increases the code quality big time.

**Comment by WiXSL** [comment]
Thank you!

**Pull request merged**
