### PR TITLE
Use framer-motion for SimpleFormIterator

### PR DESCRIPTION
**Pull request by alanpoulain**
Following https://github.com/marmelab/react-admin/pull/7426.

Use framer-motion to handle reorder animations. It also enables a drag feature.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Framer-motion is 138kb, it seems very expensive for animating 1 component

**Comment by alanpoulain** [comment]
There are some considerations [in this page](https://www.framer.com/docs/guide-reduce-bundle-size/) to take into account.
Have you another idea for a component handling this animation? Or do you want to give up the idea of animating it?

**Comment by fzaninotto** [comment]
It's be interesting to see how much weights it adds to a real app. Can you check on the simple example with `cd examples/simple && yarn build`?

**Comment by alanpoulain** [comment]
With `framer-motion`:

image

Without `framer-motion`:

image

It seems it does add at least 100Kb.

**Comment by fzaninotto** [comment]
that's too much for a single use

**Comment by CiberNin** [comment]
What about react-dnd or react-smooth-dnd? They are about a third-fourth the size. And I do think dnd would be a very nice feature to have for SimpleFormIterator, or a nice incentive to shell out for enterprise ReferenceManyInput. Maybe potentially editable datagrid, ReferenceArrayInput, or DualListInput.

**Comment by djhi** [comment]
That will be easier to do in userland with v5 so let's close this

**Pull request closed without merging**
