### PR TITLE
List view delete button

### PR DESCRIPTION
**Pull request by jayanth-1**

### CODE REVIEW

**Comment by fzaninotto** [comment]
What bug are you trying to fix?

**Comment by jayanth-2** [comment]
> What bug are you trying to fix?

this one https://github.com/marmelab/react-admin/issues/4445

**Comment by fzaninotto** [comment]
We never use `window.location.reload()` in the react-admin codebase as it reloads the entire app (and not just the data).

Also, please add a unit test showing that you've solved the bug.

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Pull request closed without merging**
