### PR TITLE
[RFR] Remove DisabledInput

### PR DESCRIPTION
**Pull request by djhi**
- [x] Remove the component
- [x] Update docs
- [x] Upgrade guide

### CODE REVIEW

**Comment by fzaninotto** [comment]
I can't find the `readOnly` prop in the material-ui documentation for `TextField`. It seems it's called `disabled`. Am I missing something?

https://material-ui.com/api/text-field/

**Comment by djhi** [comment]
You're right, according to mui documentation it should be:

```
InputProps={{
     readOnly: true,
}}
```

**Comment by fzaninotto** [comment]
But doesn't the `disabled` prop suffice?

**Comment by djhi** [comment]
`disabled` !== `readonly` semantically.

Besaides, disabled inputs won't even be sent in the form payload.

**Comment by fzaninotto** [comment]
The question is: is it our job to document this subtle distinction? Or should we encourage the simplest way (in my mind, `disabled`)?

**Pull request merged**
