### PR TITLE
Add missing Route import to Routing docs example

### PR DESCRIPTION
**Pull request by herndlm**
Just noticed that this is missing on https://marmelab.com/react-admin/Routing.html#adding-custom-pages

### CODE REVIEW

**Review by WiXSL — APPROVED** [review]

**Comment by WiXSL** [comment]
Thanks!

**Comment by fzaninotto** [comment]
Thanks!

**Comment by herndlm** [comment]
btw offtopic, the 3 -> 4 upgrade docs are really good and well-written :)

**Comment by fzaninotto** [comment]
Thanks for the feedback, we appreciate!

**Pull request merged**
