### PR TITLE
add optional labelFn prop to SimpleFormIterator

### PR DESCRIPTION
**Pull request by iamstiil**

### CODE REVIEW

**Review by djhi — COMMENTED** [review]
Can you please describe the usecase?

**Comment by iamstiil** [comment]
I created a custom input, with nested iterators. I would like to update the label in the nested iterators to `1.1`, `1.2`, etc. so that I can differentiate between `1.3` and `2.3` for example.

**Review by djhi — CHANGES_REQUESTED** [review]
Can you please add tests and update the documentation?

**Comment by iamstiil** [comment]
Sure 👍

**Pull request closed without merging**
