### PR TITLE
[RFR] Docs: Move built-in validators above custom validation

### PR DESCRIPTION
**Pull request by heyfife**
I put the easy way to do validation first followed by advanced, custom validation methods.

We had custom ``required()`` validators all over our code since that's the first way validation is described in the docs. Hopefully this reordering will help others avoid the extra, custom work when built-in functionality already exists to cover common cases.

### CODE REVIEW

**Comment by heyfife** [comment]
Yes. Will do this week.

**Comment by fzaninotto** [comment]
Again, this doesn't make sense, and the repetition of the validators makes the doc harder to read.

**Comment by heyfife** [comment]
No, it did not. I left in the built-in validation section at the top and meant to remove it. It should be clear now.

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
