### PR TITLE
Actually showing random image, instead of same image at /login

### PR DESCRIPTION
**Pull request by developerium**
Hi guys

At login, I always got the same image! I dug deeper and saw the problem was from [this address](https://source.unsplash.com/random/1600x900/daily). By removing `/daily`, you actually get random image.

What do you guys think?

### CODE REVIEW

**Comment by Kmaschta** [comment]
Actually, it was totally random at first, but we changed this behavior since it was disturbing to some of our users.

**Comment by NikitaVlaznev** [comment]
It would be great to provide a way to configure the default Login Page at least by passing background image url.

**Comment by ashim-k-saha** [comment]
@NikitaVlaznev `backgroundImage` is the prop, you can use with login component.

**Comment by JBaczuk** [comment]
@NikitaVlaznev You can pass it through admin component like this:

```
import { Admin, Login } from 'react-admin';

const MyLoginPage = () => <Login backgroundImage="/background.jpg" />;

const App = () => (
    <Admin loginPage={MyLoginPage}>
        // ...
    </Admin>
);
```

See [Using a Custom Login](https://marmelab.com/react-admin/Theming.html#using-a-custom-login-page)

**Comment by NikitaVlaznev** [comment]
Thanks!

**Comment by NikitaVlaznev** [comment]
Is it a supposed behavior that Custom login, Custom error and custom notification sections are not listed in the table of contents (Theming)?
https://marmelab.com/react-admin/Theming.html#using-a-custom-login-page

**Pull request closed without merging**
