### PR TITLE
Fix form values sanitization messes with JSON values

### LINKED ISSUE #4037: Problem with json type Inputs
**What you were expecting:**
Expected to save entered data

**What happened instead:**
Instead, react-admin modifies my input. I created JsonInput, which sends a json object to the input SimpleForm, however, a modified version of it gets into the Data Provider.

**Steps to reproduce:**
1) Add a json object type input to the data being sent
2) save record

**Related code:**
that's what is sent to the input:
```
json: {
   "FunctionalGroup": [
      {
         "uaIDref": [
            "2104"
         ],
         "_Name": "Текущие параметры",
         "_ID": "33"
      },
      {
         "uaIDref": [
            "2100"
         ],
         "_Name": "Текущие параметры пониженной точности",
         "_ID": "34"
      }
   ],
   "_Name": "Прибор 1",
   "_ID": "32"
}
```

that's what came to the server:
```
json: {
	"FunctionalGroup": [
		{
		  "uaIDref": [
			"2104"
		  ],
		  "_Name": "Текущие параметры",
		  "_ID": "33"
		},
		{
		  "uaIDref": [
			"2100"
		  ],
		  "_Name": "Текущие параметры пониженной точности",
		  "_ID": "34"
		}
	],
	"FunctionalGroupIds": "",
	"_Name": "Прибор 1",
	"_ID": "32"
},
```

after a response from the server with this object, this is what came in the field:
```
json: {
  FunctionalGroup: [
    {
      uaIDref: [
        '2104'
      ]
    },
    {
      uaIDref: [
        '2100'
      ]
    }
  ],
  FunctionalGroupIds: ''
}
```

what kind of magic is this?

I did some tests. When I converted the object to a string, the correct json was sent to the server, however, in the field after the server responded, the modified object was displayed again.
I found out that the conversion is related to redux.js, but what exactly happens is not understood.

Please give any comments on this.
How can I make save json?

* React-admin version: 3.0.0

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #4037

### CODE REVIEW

**Comment by wmwart** [comment]
@djhi, the test you used will pass and if you don’t make a change.
As I wrote the problem with objects that contain *id* or lists in their keys.
Here is what my json gives out with these changes:
```
{
   group: [
      {
         group: [
            {
               uaid: [ "10", "11", "12", "13", "14", "15", "16", "17", "18" ],
               group: [
                  {
                     uaid: [ "110", "111", "112", "113" ],
                     name: "Настройка параметров",
                     id: "2"
                  },
                  {
                     uaid: [ "14", "10", "120", "121", "122", "123", "124", "125" ],
                     name: "Синхронизация Vст",
                     id: "3"
                  }
               ],
               name: "V стандарт",
               id: "1"
            },
            {
               group: [
                  {
                     name: "Настройка параметров",
                     id: "5"
                  },
                  {
                     name: "Синхронизация Vр",
                     id: "6"
                  }
               ],
               name: "V рабочий",
               id: "4"
            },
            {
               uaid: [  "30", "37", "38", "39", "311", "312", "313", "31", "32", "33", "34", "35", "36" ],
               name: "Давление",
               id: "7"
            },
            {
               uaid: [ "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "400" ],
               name: "Температура",
               id: "8"
            },
            {
               name: "Преобразование",
               id: "9"
            },
            {
               uaid: [ "1000", "1001", "1002", "1005" ],
               group: [
                  {
                     name: "Месячный архив 1",
                     id: "101"
                  },
                  {
                     name: "Месячный архив 2",
                     id: "102"
                  },
                  {
                     name: "Суточный архив",
                     id: "103"
                  },
                  {
                     name: "Интервальный архив",
                     id: "104"
                  }
               ],
               name: "Архив",
               id: "10"
            },
            {
               uaid: [ "1100",  "1101", "1102", "1103", "1104" ],
               group: [
                  {
                     name: "Журнал событий",
                     id: "111"
                  },
                  {
                     name: "Журнал изменений",
                     id: "112"
                  }
               ],
               name: "Статус",
               id: "11"
            },
            {
               name: "Прибор",
               id: "12"
            },
            {
               name: "Сервис",
               id: "13"
            }
         ],
         name: "EK270-menu",
         id: "0"
      }
   ],
   name: "EK280"
}
```

output:

```
{
  group: [
    {
      group: [
        {
          uaid: [
            '10',
            '11',
            '12',
            '13',
            '14',
            '15',
            '16',
            '17',
            '18'
          ],
          group: [
            {
              uaid: [
                '110',
                '111',
                '112',
                '113'
              ],
              name: 'Настройка параметров',
              id: '2'
            },
            {
              uaid: [
                '14',
                '10',
                '120',
                '121',
                '122',
                '123',
                '124',
                '125'
              ],
              name: 'Синхронизация Vст',
              id: '3'
            }
          ],
          groupIds: [
            '2',
            '3'
          ],
          name: 'V стандарт',
          id: '1'
        },
        {
          group: [
            {
              name: 'Настройка параметров',
              id: '5'
            },
            {
              name: 'Синхронизация Vр',
              id: '6'
            }
          ],
          groupIds: [
            '5',
            '6'
          ],
          name: 'V рабочий',
          id: '4'
        },
        {
          uaid: [
            '30',
            '37',
            '38',
            '39',
            '311',
            '312',
            '313',
            '31',
            '32',
            '33',
            '34',
            '35',
            '36'
          ],
          name: 'Давление',
          id: '7'
        },
        {
          uaid: [
            '40',
            '41',
            '42',
            '43',
            '44',
            '45',
            '46',
            '47',
            '48',
            '49',
            '400'
          ],
          name: 'Температура',
          id: '8'
        },
        {
          name: 'Преобразование',
          id: '9'
        },
        {
          uaid: [
            '1000',
            '1001',
            '1002',
            '1005'
          ],
          group: [
            {
              name: 'Месячный архив 1',
              id: '101'
            },
            {
              name: 'Месячный архив 2',
              id: '102'
            },
            {
              name: 'Суточный архив',
              id: '103'
            },
            {
              name: 'Интервальный архив',
              id: '104'
            }
          ],
          groupIds: [
            '101',
            '102',
            '103',
            '104'
          ],
          name: 'Архив',
          id: '10'
        },
        {
          uaid: [
            '1100',
            '1101',
            '1102',
            '1103',
            '1104'
          ],
          group: [
            {
              name: 'Журнал событий',
              id: '111'
            },
            {
              name: 'Журнал изменений',
              id: '112'
            }
          ],
          groupIds: [
            '111',
            '112'
          ],
          name: 'Статус',
          id: '11'
        },
        {
          name: 'Прибор',
          id: '12'
        },
        {
          name: 'Сервис',
          id: '13'
        }
      ],
      groupIds: [
        '1',
        '4',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13'
      ],
      name: 'EK270-menu',
      id: '0'
    }
  ],
  groupIds: '',
  name: 'EK280'
}
```

ra added groupIds parameter to lists.

**Comment by fzaninotto** [comment]
Could you reduce the problem to a simpler JSON?

**Comment by wmwart** [comment]
```
{
  group: [
    {
      uaid: [
        '110',
        '111'
      ],
      name: 'Настройка  параметров',
      id: '2'
    },
    {
      uaid: [
        '14',
        '10'
      ],
      name: 'Синхронизация Vст',
      id: '3'
    }
  ],
  name: 'V стандарт',
  id: '1'
}
```
==>
```
{
  group: [
    {
      uaid: [
        '110',
        '111'
      ],
      name: 'Настройка  параметров',
      id: '2'
    },
    {
      uaid: [
        '14',
        '10'
      ],
      name: 'Синхронизация Vст',
      id: '3'
    }
  ],
  groupIds: '',
  name: 'V стандарт',
  id: '1'
}
```
ra added groupIds parameter after list.

**Comment by wmwart** [comment]
@fzaninotto, is it thrown?

**Comment by dorthwein** [comment]
So this is still happening particularly with GeoJson feature collections which can go several layers down ;(

**Comment by djhi** [comment]
Can you open a new issue following the issue template please?

**Pull request merged**
