### PR TITLE
ReferenceManyField with ra-data-graphql-simple must filter by target field name #3977

### LINKED ISSUE #3977: ReferenceManyField with ra-data-graphql-simple must filter by target field name
**What you were expecting:**

A ReferenceManyField with ra-data-graphql-simple must filter by target field name.

**What happened instead:**

ra-data-graphql-simple add 'Id' to target field name, so the filter doesn´t match with the schema when target field doesn´t end with Id.

Network error: Response not successful: Received status code 400

**Steps to reproduce:**

https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql-simple/src/buildVariables.test.js

In tests, if target field name is 'author.id', filter must be equal to "filter: { author: 'author1' }"

**Related code:**

https://github.com/marmelab/react-admin/blob/master/packages/ra-data-graphql-simple/src/buildVariables.test.js

```	
    describe('GET_MANY_REFERENCE', () => {
        it('returns correct variables', () => {
            const params = {
                target: 'author.id',
                id: 'author1',
            };

            expect(
                buildVariables()(
                    { type: { name: 'Post' } },
                    GET_MANY_REFERENCE,
                    params,
                    {}
                )
            ).toEqual({
                filter: { authorId: 'author1' },
            });
        });
    });	
```

https://github.com/marmelab/react-admin/blob/fc42fbe49f48fd93ae3210dab5d239ae6419b18a/packages/ra-data-graphql-simple/src/buildVariables.js#L251

```
case GET_MANY:
	return {
		filter: { ids: preparedParams.ids },
	};
case GET_MANY_REFERENCE: {
	const parts = preparedParams.target.split('.');
	return {
		filter: { [`${parts[0]}Id`]: preparedParams.id },
	};
```

**Environment**

* React-admin version: 2.9.8
* React version: 16.6.3
* Browser: Chrome
* ra-data-graphql-simple: 2.9.8

### PR DESCRIPTION
**Pull request by StoraH**
Closes #3977

### CODE REVIEW

**Comment by wmwart** [comment]
Why is this change not included in the release?

**Comment by ThieryMichel** [comment]
Sorry, it was not reviewed yet.
Could you rebase please ?

**Comment by canuto** [comment]
Can someone merge this so I can remove my "hack" from the client ;-)

**Comment by WiXSL** [comment]
I belive you should resolve the conflicts first. ;-)

**Comment by JulienMattiussi** [comment]
@StoraH This PR starts to be old and it just need a rebase of your branch on current master

**Comment by jdemangeon** [comment]
So, because this error breaks the demo and we can't wait much more time, I've reproduced the patch in a new PR.

https://github.com/marmelab/react-admin/pull/4685

**Pull request closed without merging**
