### PR TITLE
Rich text as json

### PR DESCRIPTION
**Pull request by RWOverdijk**
Hello again, I wanted to share another suggestion! I have this change locally and it works.

**Context**

The reason I use this:

Our front end (api consumer) is a mobile app. Instead of a webview (which looks kind of lame on a mobile phone) I use json to parse it into native components. To do this I need json instead of html.

Luckily, tiptap supports this! This tiny change allows me to store json instead of html.

**BC**

I made it backwards compatible by defaulting to html and explicitly requiring `json` to activate the new behaviour. Even if someone uses this prop it won't break.

Thoughts?

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Well that was fun 😅

**Comment by fzaninotto** [comment]
It's a nice addition! Could you PR against `next` rather than `master`, as the latter is only for bug fixes?

Also, please update the documentation and add a unit test to demonstrate the new feature.

**Comment by RWOverdijk** [comment]
@fzaninotto Sure, I'll do that tomorrow 😄

**Comment by RWOverdijk** [comment]
@fzaninotto Where are the unit tests for text input?

**Comment by RWOverdijk** [comment]
@fzaninotto why did you reopen this? I need to reapply the changes on next, this is based on master

**Comment by fzaninotto** [comment]
right, sorry!

**Pull request closed without merging**
