### PR TITLE
[RFR] Remove `FC` usage from `Field` components

### PR DESCRIPTION
**Pull request by WiXSL**

### CODE REVIEW

**Review by djhi — APPROVED** [review]
Thanks!

**Comment by fzaninotto** [comment]
I'm afraid we'll have to revert this one. To see why, try to run the demo with `make demo` in the latest master. The TS compilation fails with a weird

>Failed to compile.
>
>~/react-admin/examples/demo/src/visitors/ColoredNumberField.tsx
>TypeScript error in ~/react-admin/examples/demo/src/visitors/ColoredNumberField.tsx(15,47):
>Property 'defaultProps' does not exist on type 'NamedExoticComponent<NumberFieldProps>'.  TS2339
>
>```    13 |     ) : null;
>    14 | 
>    15 | ColoredNumberField.defaultProps = NumberField.defaultProps;
>       |                                               ^
>    16 | 
>    17 | export default ColoredNumberField;
>    18 |

The culprit is DefinitelyTyped/React, which types `React.memo` with this `NamedExoticComponent` that doesn't support defaultProps. 

This bug has been closed without fix: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36320

So although FC has drawbacks, not using FC for memoized components is worse.

**Comment by fzaninotto** [comment]
I'll make a PR to fix it

**Comment by WiXSL** [comment]
Thank you!

**Pull request merged**
