### PR TITLE
[RFR] Replace withDataProvider by Query on demo dashboard

### PR DESCRIPTION
**Pull request by Kmaschta**
Replace all the dataprovider usage on the demo dashboard by the `<Query>` component.

**Pros**
- Make the code more readable
- Suggests a better pattern to new users
- Test the `<Query>` component on a "real" usage

**Cons**
- Do a lot more requests (but can be memoized)
- No longer suggest how to use the `withDataProvider` HOC

### CODE REVIEW

**Comment by fzaninotto** [comment]
Not good: you're replacing 2 queries with 1+N queries in the orders list. This is the reason why I used `withDataProvider` in the dashboard in the first place.

**Comment by Kmaschta** [comment]
I agree, and I was also wondering if it was a real issue or not.
Since react-admin cache results in its redux store (it's often the same requests), what do we show as examples in the demo: performance vs. API?

**Comment by fzaninotto** [comment]
Both: performance in the dashboard, API in the review moderation buttons.

**Comment by Kmaschta** [comment]
Ok, my bad!

**Pull request closed without merging**
