### PR TITLE
Add 'icon' prop to buttons

### PR DESCRIPTION
**Pull request by afilp**
We had the need to customize the icon shown on the `ShowButton`.

This commit changes just the `ShowButton`, so that you comment whether you like this change or not.

If you agree with this, let me know so that we also update the rest of the buttons located inside the `button` folder.

Thanks.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Love it! Would you mind going a bit further and do the same for other buttons?

**Comment by afilp** [comment]
Sure! That was the idea! First to see if you want it, then take the time to do the rest. I will do this most likely during the weekend.

Thanks!

**Comment by afilp** [comment]
Added 2nd commit for the rest of the buttons.

Please note that in some "class"-using buttons I moved the `propTypes` and `defaultProps` as `static`. This was done for consistency (some classes used the `static` approach, others the named declaration at the end).

**Comment by djhi** [comment]
Thanks!

**Pull request merged**
