### PR TITLE
Add support for success notification type

### PR DESCRIPTION
**Pull request by WiXSL**
Supersedes #5624

### CODE REVIEW

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Thanks!

**Comment by fzaninotto** [comment]
I realize this changes the color of all the default notifications in a way I really don't like. It feels like a regression to me.

I'll revert this PR (and #5724) so that we can rediscuss that without blocking 3.12, which is around the corner.

**Comment by fzaninotto** [comment]
In particular, the "Undo" is not visible

image

**Comment by WiXSL** [comment]
Ok.
I will love to have `success`, `info`, `warning` and `error` colors anyways in the future, since right now, notifications warning and error colors are both red and success and info are both black.
Let me now if aI can make a related PR.

**Pull request merged**
