### PR TITLE
Fix hide filters with brackets in source

### PR DESCRIPTION
**Pull request by yanchesky**
Fixes https://github.com/marmelab/react-admin/issues/8572

### CODE REVIEW

**Comment by yanchesky** [comment]
I have thought it through and It may be wrong to change `useList` and `useReferenceManyFieldController` hiding filter implementation. It is `useListParams`'s responsibility to show filters that way. Therefore, only its hide function should work with regard to how the show function works. Changing in other places could break someone's implementation. Am I right or not? 🤔

**Comment by slax57** [comment]
Thanks for providing this PR.
Having read through it rapidly, I believe you are correct, it would rather be `useListParams`'s responsibility imo.

Also, have you seen [@fzaninotto's comment here](https://github.com/marmelab/react-admin/issues/8572#issuecomment-1404949164)?
To me this calls the need for this change into question.
Do you have a use-case that would justify its need?

**Comment by yanchesky** [comment]
I don't really have a use case for this. However, I think that `useListParams`'s **showFilter** and **hideFilter** functions should work complementary. If one function converts dot and bracket notation, then the other should work accordingly.

**Comment by fzaninotto** [comment]
If there is no bug, don't fix it ;)

**Comment by fzaninotto** [comment]
No traction for this, so I'll close this PR. Thanks for your changes anyway, and don't hesitate to open more PRs!

**Pull request closed without merging**
