### PR TITLE
Change filter extend order in ReferenceInputController

### LINKED ISSUE #3739: Changing filter in `ReferenceArrayInput` does change the filter added to the `GET_LIST` action.
**What you were expecting:**

Updating filter in `ReferenceArrayInput` should update the filter added in the `GET_LIST` API call.

**What happened instead:**

Updating filter in `ReferenceArrayInput` does not update filter in the API call. Uses the stale filter.

**Steps to reproduce:**

https://codesandbox.io/s/simple-cop17?fontsize=14

Try to create a Post `/posts/create` which has a `ReferenceArrayInput` for searching a user. You can see in the browser console action logger that the `filter` in the `GET_LIST` call is one form change old.
image

See in the screenshot above - the user input for email does not match the filter in the action.

**Other information:**

I believe this is happening because the `fetchOptions` in the line [203](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx#L203) in `ReferenceArrayInputController` is called without passing the `nextProps` as argument which means the `defaultFilter` in line [262](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/ReferenceArrayInputController.tsx#L262) is still the old filter.

**Environment**

* React-admin version: ^2.9.5
* Last version that did not exhibit the issue (if applicable):
* React version:^16.8.6
* Browser:Chrome
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by TheHyphen**
Closes #3739

### CODE REVIEW

**Comment by djhi** [comment]
Thanks! Would you mind adding a test for this?

**Comment by TheHyphen** [comment]
Done, added tests now.

**Comment by TheHyphen** [comment]
When do you think this might make it to a release?

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
