### PR TITLE
[RFR] Pass confirmColor from DeleteButton to Confirm

### LINKED ISSUE #9322: Make Confirm's confirmColor passable from DeleteButton
**Is your feature request related to a problem? Please describe.**
One of our team members expressed a concern that confirm to delete dialog's buttons are both primary color. They asked me if I could make the confirm one red, so I did a dive and apparently `Confirm` component supports `confirmColor` prop, but there's no way to pass it from `DeleteButton` component.

### PR DESCRIPTION
**Pull request by IAmVisco**
Closes #9322

### CODE REVIEW

**Review by slax57 — APPROVED** [review]
LGTM, thanks!

**Review by slax57 — CHANGES_REQUESTED** [review]
Oh, one more thing actually, could you please also document this prop in [Buttons.md](https://github.com/marmelab/react-admin/blob/master/docs/Buttons.md?plain=1#L657)?
Thanks

**Comment by IAmVisco** [comment]
Shoot, completely forgot about that one. Will do!

**Review by slax57 — APPROVED** [review]
Thanks!

**Pull request merged**
