### PR TITLE
[RFR] RichTextInput - allow fullWidth

### PR DESCRIPTION
**Pull request by natrim**
pass fullWidth in RichTextInput to FormControl be able to make the wysiwyg full width

### CODE REVIEW

**Comment by natrim** [comment]
maybe it could even be true by default as in LongTextInput ?

**Comment by natrim** [comment]
@djhi should be done

**Comment by fzaninotto** [comment]
This is a new feature: it should have been PRed against `next`, not `master`. I'm going to revert it, could you please PR again against `next`? 

Sorry for the inconvenience.

**Comment by natrim** [comment]
@fzaninotto reopen as #2253

**Pull request merged**
