### PR TITLE
Fix right sidebar scrolling on documentation pages

### PR DESCRIPTION
**Pull request by gitstart**
### Description 
The right sidebar now hides when the height is reduced to a certain level.

### Fixes
Fixes: #7589

### Screenshots
**Large Screen:** 

**Reduced Screen:**

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
> I don't understand why you hide the TOC in this case. It's not a good fix for #7589 IMHO.

As per the comment [here](https://github.com/marmelab/react-admin/issues/7589#issuecomment-1114241660) It was suggested to hide it.
But if you have another solution in mind, kindly let us know and we'll make changes accordingly.

**Comment by fzaninotto** [comment]
That was a bad idea (I know it was mine ;)) It would hide the TOC even when it's small enough to fit on the screen. 

I don't have a better solution in my head.

**Comment by gitstart** [comment]
> That was a bad idea (I know it was mine ;)) It would hide the TOC even when it's small enough to fit on the screen.
> 
> I don't have a better solution in my head.

What if we make the TOC scrollable?

**Comment by fzaninotto** [comment]
> What if we make the TOC scrollable?

Yes! If you can update your PR to do that, we'll merge it.

**Comment by gitstart** [comment]
> > What if we make the TOC scrollable?
> 
> Yes! If you can update your PR to do that, we'll merge it.

The ToC is now scrollable @fzaninotto

**Comment by slax57** [comment]
Superseded by https://github.com/marmelab/react-admin/pull/8898

**Pull request closed without merging**
