### PR TITLE
Add `component` prop to TabbedForm component

### PR DESCRIPTION
**Pull request by WiXSL**
Like `SimpleForm` has.
This allows to have access to the children inside the form without rewriting everything.

### CODE REVIEW

**Review by djhi — APPROVED** [review]
:+1:

**Review by fzaninotto — CHANGES_REQUESTED** [review]

**Comment by fzaninotto** [comment]
I realize that with my requested changes, your PR is now a breaking change. A developer can no longer override the content className by overriding the `classes` prop.

So I don't think we'll merge this before 4.0 (which is not yet schedules). 

Besides, something bothers me in this PR. I don't understand the use case. What does this PR allow that isn't yet possible with the CSS API?

**Comment by WiXSL** [comment]
It also allows to insert logic with the use `react-final-form` hooks, since we are inside the `<form>`

**Comment by fzaninotto** [comment]
> It also allows to insert logic with the use of `react-final-form` hooks, since we are inside the `<form>`

Can you elaborate?

**Comment by WiXSL** [comment]
I'll give you a more concrete use case.
A custom React context to show/hide progress blocking form inputs programmatically.


```jsx
const ProgressProvider = ({ children }) => {
    const [open, setOpen] = useState(false);

    const context = useMemo(
        () => ({
            open,
            showProgress: () => setOpen(true),
            hideProgress: () => setOpen(false)
        }),
        [open]
    );

    return (
        <ProgressContext.Provider value={context}>
            {children}
        </ProgressContext.Provider>
    );
};

const ComponentInner = props => {
    const cls = useStyles(props);
    const context = useContext(MyContext);

    return (
        <CardContentInner className={context.open ? cls.block : ''}>
            {context.open && <CircularProgress
                className={cls.progress}
                thickness={4}
                size={50}
            />}
            {props.children}
        </CardContentInner>
    );
};

const ChildrenContainer = props => (
    <ProgressProvider>
        <ComponentInner {...props} />
    </ProgressProvider>
);

<TabbedForm component={ChildrenContainer}/>

**Comment by fzaninotto** [comment]
In your use case, why can't you wrap the entire TabbedForm in your context?

**Comment by WiXSL** [comment]
Because I only want to visually block the inputs visual area, on the entire view, plus this allows me to use `react-final-form` hooks in my `ComponentInner` since I'm inside the form

**Comment by fzaninotto** [comment]
This PR was automatically closed by GitHub, I'm reopening it. Sorry for the noise.

**Comment by WiXSL** [comment]
This one was closed automatically but valid

**Comment by WiXSL** [comment]
Is it too late to add this to `next`?

**Comment by WiXSL** [comment]
Implemented by #7348

**Pull request closed without merging**
