### PR TITLE
Renamed Passwords.md to Authorization.md

### LINKED ISSUE #10294: Dead link in Authentication docs
At the end of [this page](https://marmelab.com/react-admin/Authentication.html) there is a dead link:  [Authorization](https://marmelab.com/react-admin/Authorization.md)

### PR DESCRIPTION
**Pull request by 5AIPAVAN**
closes #10294 
## Problem
Dead link in Authentication docs
## Solution
Renamed Passwords.md to Authorization.md

### CODE REVIEW

**Review by djhi — CHANGES_REQUESTED** [review]
Thanks @5AIPAVAN but we meant to change the link, not the page itself

**Comment by slax57** [comment]
Sorry  @5AIPAVAN , I read your comment a bit too fast in https://github.com/marmelab/react-admin/issues/10294 , but yeah, please update the link instead. Thanks.

**Comment by 5AIPAVAN** [comment]
> Sorry @5AIPAVAN , I read your comment a bit too fast in #10294 , but yeah, please update the link instead. Thanks.

ok i will

**Comment by djhi** [comment]
Superseded by #10303. Thanks for the report!

**Pull request closed without merging**
