### PR TITLE
[SimpleList] deprecate linkType, and implement rowClick as for the DataGrid

### PR DESCRIPTION
**Pull request by quentin-decre**
## Problem

The linkType for SimpleList provides less functionality than the rowClick for DataGrid. And also the inconsistency makes it harder to use.

## Solution

Implement rowClick prop as it works for Datagrid.
Keep the linkType prop working as previously, but show it as deprecated. If both are set, linkType takes precedence (because it will be simpler to remove from the code later that way).

## How To Test

Similar to data grid

## Additional Checks

- [ ] The PR targets `master` for a bugfix, or `next` for a feature
- [ ] The PR includes **unit tests** (if not possible, describe why)
- [X] The PR includes one or several **stories** (if not possible, describe why)
- [X] The **documentation** is up to date

### CODE REVIEW

**Review by djhi — COMMENTED** [review]
Thanks! This is a new feature though. Can you target the `next` branch?

**Comment by quentin-decre** [comment]
> Thanks! This is a new feature though. Can you target the `next` branch?

J'ai rebase sur next et changé la target, mais je ne comprends pas pourquoi il met autant de diff. Ce sont bien des commits qui sont déjà sur next non ?

**Comment by erwanMarmelab** [comment]
> > Thanks! This is a new feature though. Can you target the `next` branch?
> 
> J'ai rebase sur next et changé la target, mais je ne comprends pas pourquoi il met autant de diff. Ce sont bien des commits qui sont déjà sur next non ?

@quentin-decre 

Malheuresement non. Comme vous pouvez le voir dans le [CHANGELOG de la branche `next`](https://github.com/marmelab/react-admin/blob/next/CHANGELOG.md), la dernière version est la 5.3.0  contrairement au [CHANGELOG présent dans votre branche](https://github.com/marmelab/react-admin/blob/bb9177efc965df57bd75998654269019b0c75ec4/CHANGELOG.md) qui va jusqu'à la version 5.3.3 (comme le [CHANGELOG de la branche `master`](https://github.com/marmelab/react-admin/blob/master/CHANGELOG.md)).

Pourriez-vous recréer une nouvelle branche (basée sur `master`) et faire un `cherry-pick` de vos commits ?

**Comment by djhi** [comment]
We just merged master on next, can you rebase?

**Comment by djhi** [comment]
Closed in favor of #10385

**Pull request closed without merging**
