### PR TITLE
[RFR] Provide empty string to label prop of SearchInput

### PR DESCRIPTION
**Pull request by jaytula**
In the example/simple and example/demo app, the `SearchInput` component is used without a `label` prop and because the `label` prop has a default of `false`, this generates a translate warning.

image

This PR simply provides an empty string for the label prop of `SearchInput` whereever it is used in the example/simple and example/demo app.

### CODE REVIEW

**Comment by djhi** [comment]
Wouldn't the proper fix be to not output a label at all in `TextInput` if `label === false` ?

**Comment by jaytula** [comment]
Good point. I'll give that a try.

**Comment by djhi** [comment]
Sorry, maybe not in `TextInput` but rather in `FieldTitle` which should return `null` if `label` strictly equals to `false`.

**Comment by jaytula** [comment]
Ok.  So that means leave `<TextInput label={false}>` as is and change the the `FieldTitle` (nested under `ResettableTextField` label prop to `label === false ? null : label` in `TextInput.tsx`?

**Comment by djhi** [comment]
Nope, I meant changing `https://github.com/marmelab/react-admin/blob/next/packages/ra-core/src/util/FieldTitle.tsx` so that it returns `null` if `label === false`

**Comment by jaytula** [comment]
Ah, I see.  Thanks!  Will get to it tomorrow morning.

**Comment by jaytula** [comment]
I get a TypeScript warning after making the change because `label` is not expected to be `boolean`  in the `FieldTitle` component.

image

If I change the typing to be either `string | boolean` the red squiggles move to `getFieldLabelTranslationArgs` because it also expects the `label` to be a `string`:

image

Upon inspecting `getFieldLabelTranslationArg.ts` https://github.com/marmelab/react-admin/blob/38fc6290d573da4d9128360916ff5954a9b62727/packages/ra-core/src/util/getFieldLabelTranslationArgs.ts, this function also expects the `label` prop in the `Args` interface to be a `string` as well as the the first value (i.e. `label`) of the returned array (as specified in `TranslationArguments`.

It appears that more components and functions expect the `label` to be purely a `string` or `undefined` but not `boolean`.  Please let me know your thoughts on how best to fix it.  Thanks for helping me dig and understand this better.

**Comment by djhi** [comment]
Just convert the label to string if not equal to `false` ? `label.toString()` to be sure ?

**Comment by fzaninotto** [comment]
I believe `SearchInput` should set the label to `''` instead of `false`, *and* that `FieldTitle` shouldn't try to call `translate` if the label is falsy.

**Comment by jaytula** [comment]
@fzaninotto Setting label as `<SearchInput label="" />` works fine but not calling `translate` if `FieldTitle` is falsy results in failing unit-tests because the `source` prop is used by `translate` when `label` is falsy.  

Just to be clear, this is what I changed `FieldTitle.tsx` to:

```javascript
import React, { SFC } from 'react';
import pure from 'recompose/pure';

import useTranslate from '../i18n/useTranslate';
import getFieldLabelTranslationArgs from './getFieldLabelTranslationArgs';

interface Props {
    isRequired?: boolean;
    resource?: string;
    source?: string;
    label?: string;
}

export const FieldTitle: SFC<Props> = ({
    resource,
    source,
    label,
    isRequired,
}) => {
    const translate = useTranslate();
    return (
        <span>
            {label ? translate(
                ...getFieldLabelTranslationArgs({ label, resource, source })
            ) : ''}
            {isRequired && ' *'}
        </span>
    );
};

// wat? TypeScript looses the displayName if we don't set it explicitly
FieldTitle.displayName = 'FieldTitle';

export default pure(FieldTitle);
```
Here is the result summary of `make test-unit`:

image

**Comment by fzaninotto** [comment]
This PR needs rebase.

**Comment by jaytula** [comment]
> This PR needs rebase.

It looks like the original issue has been resolved in the `next` branch because the component is now provided with an empty string default for the `label` prop.

I'll go ahead and close this.

**Pull request closed without merging**
