### PR TITLE
Fixed wrong scalar types into variables for ra-data-graphql-simple

### PR DESCRIPTION
**Pull request by Artexoid**
The fix for GraphQL version 14.0.0+ related scalar value coercion. The current version doesn't work correctly. GraphQL changes: https://www.libupdate.com/libs/1c88bd1e-024d-41aa-9241-c29cd6d5f0c5

### CODE REVIEW

**Comment by djhi** [comment]
Sorry, the tests are currently a PITA to maintain. I'll have to clear some of them.

**Comment by Artexoid** [comment]
@djhi Also, I fixed a little bug for it

**Comment by Artexoid** [comment]
> Thanks! Can you please run prettier on this file? There is a make command for it, and a yarn one if you can't run make

Ok, I'll do now

**Comment by djhi** [comment]
Btw, I'm afraid this will be a breaking change for those who haven't upgraded their graphql package. Can you confirm ?

**Comment by Artexoid** [comment]
> Btw, I'm afraid this will be a breaking change for those who haven't upgraded their graphql package. Can you confirm ?

@djhi It works well for me. I tested it with graphql@0.13.2 and graphql@14.1.1 . The update related only with scalar values coercion to correctly types. 

Started from version 14.0.0 graphQL server throws an error if the client send in variables wrong type. For example on the server args

{
  id: Int
}

And the client send

{
  "id": "24"
}

It will work before version 14.0.0, but started from version 14.0.0 the server will return error "wrong type".

Just need to complete tests with green result :-)

**Comment by Artexoid** [comment]
It will works for old GraphQL packages too

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
