### PR TITLE
Ordered array list

### PR DESCRIPTION
**Pull request by marknelissen**
This is my take on an implementation of the OrderedFormIterator that allows drag and drop. It uses [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) . This does come with the limitation that it is not possible currently to nest orderable list inputs. The OrderedFormIterator is employed in the exact same manner as the SimpleFormIterator.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Awesome! Looking forward to using this component in our own projects. 

However, we want to keep the bundle size as small as possible - that's why the rich text input is in a standalone package. 

So I'd prefer if you published it as a standalone package on your own. You can PR against the Input documentation to mention your component in [the list of third-party components](https://marmelab.com/react-admin/Inputs.html#third-party-components).

**Comment by langhard** [comment]
@marknelissen Do you have any plans to make a third-part component?

**Comment by marknelissen** [comment]
@langhard , we moved away from using react-admin, and as such I don't feel confident in providing the solution as a third party component, seeing as we won't be able to properly support it.

You can still view the original code in the pull request. Feel free to use it in your project or publish it as a third party component.

**Comment by langhard** [comment]
Ok, thx!

**Comment by red1** [comment]
@marknelissen can you though provide an example usage of your component ?
I'm trying to replace this : 
```
import OrderedFormIterator from './OrderedFormIterator';

...
                    <SimpleFormIterator>
                        <ImageInput source="pictures" label="Related pictures" accept="image/*">
                            <ImageField source="image"  title="title" />
                        </ImageInput>
                        <TextInput  source="title" />
                        <RichTextInput source="highlighted_text" />
                    </SimpleFormIterator>
```
with
...
                    <OrderedFormIterator>
                        <ImageInput source="pictures" label="Related pictures" accept="image/*">
                            <ImageField source="image"  title="title" />
                        </ImageInput>
                        <TextInput  source="title" />
                        <RichTextInput source="highlighted_text" />
                    </OrderedFormIterator>
```
as you said 

> The OrderedFormIterator is employed in the exact same manner as the SimpleFormIterator.

But I got the following error : 
```
Error: Invariant failed: Draggable requires a draggableId

    in Draggable (created by Connect(Draggable))
    in Connect(Draggable) (at DraggableFormInput.js:64)
    in DraggableFormInput (created by WithStyles(DraggableFormInput))
    in WithStyles(DraggableFormInput) (created by Context.Consumer)
    in translate(WithStyles(DraggableFormInput)) (at OrderedFormIterator.js:110)
    in Transition (created by CSSTransition)
    in CSSTransition (at OrderedFormIterator.js:105)
    in div (created by TransitionGroup)
    in TransitionGroup (at OrderedFormIterator.js:103)
    in ul (at OrderedFormIterator.js:101)
    in DroppableDimensionPublisher (created by Droppable)
    in Droppable (created by Connect(Droppable))
    in Connect(Droppable) (at OrderedFormIterator.js:99)
    in DragDropContext (at OrderedFormIterator.js:98)
    in OrderedFormIterator (created by WithStyles(OrderedFormIterator))
    in WithStyles(OrderedFormIterator) (created by Context.Consumer)
    in translate(WithStyles(OrderedFormIterator)) (at pages/index.js:61)
    in Unknown (created by ConnectedFieldArray)
    in ConnectedFieldArray (created by Connect(ConnectedFieldArray))
    in Connect(ConnectedFieldArray) (created by FieldArray)
    in FieldArray (created by ArrayInput)
    in div (created by FormControl)
    in FormControl (created by WithStyles(FormControl))
    in WithStyles(FormControl) (created by ArrayInput)
    in ArrayInput (created by DefaultValueView)
    in DefaultValueView (created by Connect(DefaultValueView))
    in Connect(DefaultValueView) (at pages/index.js:56)
    in div (created by FormInput)
    in FormInput (created by WithStyles(FormInput))
    in WithStyles(FormInput) (created by FormTab)
    in span (created by FormTab)
    in FormTab (created by Context.Consumer)
    in translate(FormTab) (at pages/index.js:55)
    in Route (created by TabbedForm)
    in div (created by CardContent)
    in CardContent (created by WithStyles(CardContent))
    in WithStyles(CardContent) (created by CardContentInner)
    in CardContentInner (created by WithStyles(CardContentInner))
    in WithStyles(CardContentInner) (created by TabbedForm)
    in form (created by TabbedForm)
    in TabbedForm (created by WithStyles(TabbedForm))
    in WithStyles(TabbedForm) (created by Form(WithStyles(TabbedForm)))
    in Form(WithStyles(TabbedForm)) (created by Connect(Form(WithStyles(TabbedForm))))
    in Connect(Form(WithStyles(TabbedForm))) (created by ReduxForm)
    in ReduxForm (created by Context.Consumer)
    in translate(ReduxForm) (created by Connect(translate(ReduxForm)))
    in Connect(translate(ReduxForm)) (created by Route)
    in Route (created by withRouter(Connect(translate(ReduxForm))))
    in withRouter(Connect(translate(ReduxForm))) (at pages/index.js:49)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Card)
    in Card (created by WithStyles(Card))
    in WithStyles(Card) (created by EditView)
    in div (created by EditView)
    in EditView (created by UnconnectedEditController)
    in UnconnectedEditController (created by Context.Consumer)
    in translate(UnconnectedEditController) (created by Connect(translate(UnconnectedEditController)))
    in Connect(translate(UnconnectedEditController))
    in Unknown (created by Edit)
    in Edit (created by WithStyles(Edit))
    in WithStyles(Edit) (at pages/index.js:48)
    in PageEdit (created by WithPermissions)
    in WithPermissions (created by Connect(WithPermissions))
    in Connect(WithPermissions) (created by getContext(Connect(WithPermissions)))
    in getContext(Connect(WithPermissions)) (created by Route)
    in Route (created by Resource)
    in Switch (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource) (at App.js:27)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Route)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Route)
    in Route (created by withRouter(WithStyles(Layout)))
    in withRouter(WithStyles(Layout)) (created by Connect(withRouter(WithStyles(Layout))))
    in Connect(withRouter(WithStyles(Layout))) (created by LayoutWithTheme)
    in MuiThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (created by Route)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Connect(CoreAdminRouter))
    in Connect(CoreAdminRouter) (created by getContext(Connect(CoreAdminRouter)))
    in getContext(Connect(CoreAdminRouter)) (created by Route)
    in Route (created by CoreAdminBase)
    in Switch (created by CoreAdminBase)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by CoreAdminBase)
    in TranslationProviderView (created by Connect(TranslationProviderView))
    in Connect(TranslationProviderView) (created by CoreAdminBase)
    in Provider (created by CoreAdminBase)
    in CoreAdminBase (created by withContext(CoreAdminBase))
    in withContext(CoreAdminBase) (at App.js:25)
    in App (at src/index.js:7)
```

**Comment by marknelissen** [comment]
When I wrote the implementation, something like the following worked:

```
const InspectionForm = ({ classes, record, resource }) => (
    <ArrayInput source="steps" resource={resource} record={record}>
        <OrderedFormIterator resource={resource}>
            <TextInput source="location" label="Location" formClassName={classes.inlineBlock} />
            <TextInput source="description" label="Description" formClassName={classes.inlineBlock} />
            <SelectInput source="actions" label="Actions" formClassName={classes.inlineBlock} choices={[
                { id: 'to do', name: 'to do' }
            ]} />
            <ImageInput source="photo" label="Photo" accept="image/*" formClassName={classes.inlineBlock} >
                <ImageField source="src" title="title" />
            </ImageInput>
            <ImageInput source="snapshot" label="3D Model Snapshot" accept="image/*" formClassName={classes.inlineBlock} >
                <ImageField source="src" title="title" />
            </ImageInput>
        </OrderedFormIterator>
    </ArrayInput>
);
```
How did you add the OrderedFormIterator? Did you copy/paste it into your own code or did you take my entire branch?

I noticed that the current implementation of SimpleFormIterator in react-admin handles id generation slightly differently, that might be causing this behaviour. The ids are generated in the constructor of the OrderedFormIterator.

**Pull request closed without merging**
