### PR TITLE
Fix :  possibility to add label to rowsPerPageOptions prop of TablePagination component

### LINKED ISSUE #8609: Possibility to add label to rowsPerPageOptions prop of TablePagination component
**Is your feature request related to a problem? Please describe.**
I need to have customizable label in rowsPerPageOptions prop of TablePagination component like in mui

**Describe the solution you'd like**
I want to change prop type of rowsPerPageOptions prop from number[] to { label: string; value: number; } | number[] like it is in mui

**Describe alternatives you've considered**
-

**Additional context**
image
image

### PR DESCRIPTION
**Pull request by NidhiSharma63**
close #8609

### CODE REVIEW

**Review by djhi — CHANGES_REQUESTED** [review]
Hi and thank you for contributing! Can you please add a storybook story about this, and tests? Can you also update the documentation?

**Comment by NidhiSharma63** [comment]
@djhi i didn't figure out the way to run the test. don't see any script

**Comment by djhi** [comment]
> @djhi i didn't figure out the way to run the test. don't see any script

It's explained in the main README: https://github.com/marmelab/react-admin?tab=readme-ov-file#automated-tests

**Comment by NidhiSharma63** [comment]
> > @djhi i didn't figure out the way to run the test. don't see any script
> 
> It's explained in the main README: https://github.com/marmelab/react-admin?tab=readme-ov-file#automated-tests

sorry but it's not my cup of tea 😐. i tried but test are no running getting error. and also i don't know how to write story book as well.
Thank you for your time

**Comment by fzaninotto** [comment]
Sorry, we can't merge a PR that doesn't contain automated tests. If you can't add them, we'll close this PR.

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Pull request closed without merging**
