### PR TITLE
With 'daily' suffix there is one picture all the time

### PR DESCRIPTION
**Pull request by NikitaVlaznev**
Without 'daily' it's random.

### CODE REVIEW

**Comment by Kmaschta** [comment]
Duplicate of #2964

But I agree, unslash is bugging :(

**Comment by fzaninotto** [comment]
When you write "all the time", do you mean during more than one day? could it be because you're behind an aggressive proxy / CDN ?

**Comment by Kmaschta** [comment]
@fzaninotto It's been weeks that unslash didn't changed the image at `https://source.unsplash.com/random/1600x900/daily`, and that every react admin have now the same login background.


unslash daily image

**Comment by fzaninotto** [comment]
I've sent an email to the Unsplash support to determine of the feature is temporarily disabled or broken.

**Comment by fzaninotto** [comment]
This seems to be fixed, closing

**Pull request closed without merging**
