### PR TITLE
fix demo dependency

### PR DESCRIPTION
**Pull request by thenotsoft**

### CODE REVIEW

**Comment by Luwangel** [comment]
Hello @thenotsoft, thanks for contributing.

Could you add a description to help me understand the goal of your PR? What is wrong with the current dependencies?

**Comment by anddann** [comment]
Thx a lot for this PR! I tried to run the demo with `npm install` and `npm` start but I always got the error "please install types/react-router-dom"

**Comment by fzaninotto** [comment]
You should use the `make` commands, as explained in the README.

```
# At the react-admin project root
make install
# Run the demo application
make build
make run-demo
```

**Comment by thenotsoft** [comment]
I tried to raise under Windows with the help of make commands, but something went wrong, and already manually, and until I installed these dependencies, it did not start, if this is not necessary, you can close the PR

**Pull request closed without merging**
