### PR TITLE
Fix create-react-admin does not include its templates

### PR DESCRIPTION
**Pull request by djhi**

### CODE REVIEW

**Review by slax57 — APPROVED** [review]

**Comment by dnk8n** [comment]
I am running into this? Is there a workaround?

**Comment by slax57** [comment]
> I am running into this? Is there a workaround?

@dnk8n  I guess you could paste the missing `templates` folder in your `~/.config/yarn/global/node_modules/create-react-admin` (this is for yarn, might require adaptation for npm), even though this is of course really ugly :shrug:

**Comment by dnk8n** [comment]
Note, need to do it mid installation. Copying the templates before, causes them to be cleared out again.

**Comment by fzaninotto** [comment]
We'll release a new version shortly that removes the need for this manual copy / paste.

**Comment by joanllodrariera** [comment]
Since this upgrade I'm receiving the error: [commonjs--resolver] Failed to resolve entry for package "ra-language-french". The package may have incorrect main/module/exports specified in its package.json.

**Pull request merged**
