### PR TITLE
[Docs] Update third-party component reference to new dateinput library

### PR DESCRIPTION
**Pull request by ZachSelindh**
The Third-Party Components section of the docs previously directed users seeking DateInput components to a now-deprecated library which had not been maintained since react-admin v3, and was not compatible with MUI v5.

This PR updates the docs to direct users to a package that I have deployed to npm, containing the pickers which I have used in my current project for the last couple of years. These pickers are fully MUI v5-compatible and use the latest react-admin standards (InputHelperText component, current patterns of useInput, etc.).

Thanks!

### CODE REVIEW

**Comment by fzaninotto** [comment]
Excellent! Although your code misses a Licence. Is it open-source?

**Comment by ZachSelindh** [comment]
> Excellent! Although your code misses a Licence. Is it open-source?

Thanks for pointing that out! I had MIT license in the package.json but I've also added a license section to the readme.

**Comment by fzaninotto** [comment]
You should add a LICENSE file, so that GitHub can tag your repo as MIT.

**Comment by ZachSelindh** [comment]
> You should add a LICENSE file, so that GitHub can tag your repo as MIT.

Done. Thanks! This is my first npm package and I appreciate the feedback.

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
The `next` branch is to be published within a month. For doc changes, please PR against the `master` branch, which we release weekly.

**Pull request closed without merging**
