### PR TITLE
Fix datagrid error

### PR DESCRIPTION
**Pull request by alexicum**
Uncaught TypeError: Cannot read property 'field' of undefined

Check that currentSort is available, because it is not required.

### CODE REVIEW

**Comment by alexicum** [comment]
I'm using Datagrid alone to show second list near resource List.
Here it is. Removing `currentSort={{}}` will cause this warning:

```
render() {
    return (
      <Datagrid className={styles.DbProducts} data={this.props.data} ids={this.props.ids} currentSort={{}}>
        <TextField source="id" />
        <TextField source="name" />
      </Datagrid>
    );
  }
```

**Comment by fzaninotto** [comment]
`<Datagrid>` is supposed to be used inside `<List>` or `<ReferenceManyField>`. Both inject the `currentSort` prop. If you use it outside of the normal use cases, you should respect the same convention and inject a default sort, too.

As far as I understand, your use case isn't standard and we don't want to support it. So I'm closing this PR. Feel free to reopen if you disagree.

**Comment by alexicum** [comment]
May be it would be better to make currentSort required in Datagrid and DatagridHeaderCell?

**Comment by fzaninotto** [comment]
You're right. Would you like to open a PR for that?

**Comment by alexicum** [comment]
https://github.com/marmelab/react-admin/pull/1970

**Pull request closed without merging**
