### PR TITLE
[ra-input-rich-text] Do not show error message, if input isn't touched

### LINKED ISSUE #3207: [ra-input-rich-text] validation message shows up when field isn't touched
**What you were expecting:**

I expect no validation message, when input wasn't touched yet (same as regular input)

**What happened instead:**

Validation message is visible when field is untouched.

**Steps to reproduce:**

1. Run simple example
2. Go to PostCreate.js
3. Add `validate={[required()]}` to `RichTextInput`

**Other information:**

Screenshot 2019-05-09 at 16 06 18

There's no check if field is touched (like in other inputs).
I'll submit a PR

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes #3207

### CODE REVIEW

**Comment by djhi** [comment]
Thanks!

**Comment by fzaninotto** [comment]
Something is wrong with this patch. If the form is submitted but the user didn't touch the field, I expect the error message to show up. Now it doesn't do that anymore. Please open a new PR to fix that or I'll have to revert this patch.

**Comment by cherniavskii** [comment]
I suppose, it's because of `shouldComponentUpdate` is blocking rerenders.
I've fixed that in #3209, could you check that?

**Comment by cherniavskii** [comment]
@fzaninotto checked it, it is fixed by #3209

**Comment by fzaninotto** [comment]
#3209 breaks other things, I can't merge it. So I'm going to roll back this one.

**Comment by fzaninotto** [comment]
Superseded by #3223

**Pull request merged**
