### PR TITLE
Update NotificationType type.

### PR DESCRIPTION
**Pull request by hieusmiths**
Addi success type

### CODE REVIEW

**Comment by hieusmiths** [comment]
With Notification, i think we should support success type for sync with material or some thing operator between info and success

**Comment by djhi** [comment]
If we want to support a `success` variant, this PR should also update the custom styles in the `Notification` component as we don't ues the `Alert` component from material-ui. I'm not sure we want this variant though. Ping @fzaninotto

**Comment by hieusmiths** [comment]
> If we want to support a `success` variant, this PR should also update the custom styles in the `Notification` component as we don't ues the `Alert` component from material-ui. I'm not sure we want this variant though. Ping @fzaninotto

Okay, I will update the custom style for Notification success type more.

**Comment by fzaninotto** [comment]
I'm OK with adding this level

**Comment by fzaninotto** [comment]
Any updates on this one?

**Comment by hieusmiths** [comment]
> Any updates on this one?

Now I don't have time for an update, maybe is future.

**Comment by fzaninotto** [comment]
Superseded by #5710

**Pull request closed without merging**
