### PR TITLE
Fix leading character in AutocompleteInput can not be deleted

### PR DESCRIPTION
**Pull request by septentrion-730n**
Fix https://github.com/marmelab/react-admin/issues/7935

### CODE REVIEW

**Review by djhi — CHANGES_REQUESTED** [review]
Can you add a test?

**Review by vanessa-sun — APPROVED** [review]

**Comment by vanessa-sun** [comment]
Thank you for the PR!

**Comment by afilp** [comment]
Can this be merged please, even without a test? Thanks a lot!

**Review by fzaninotto — APPROVED** [review]

**Comment by davidhenley** [comment]
Thanks! This was really bugging me.

**Pull request merged**
