### PR TITLE
ra-data-graphql-simple: Fix filter id applied incorrectly to get many ref

### PR DESCRIPTION
**Pull request by redorb**
Fixes issue #2571

### CODE REVIEW

**Comment by Redorb** [comment]
I'll check the failing tests when I get home.

**Comment by Redorb** [comment]
@fzaninotto So I was looking at my actual fix I put in a week or so back in my own codebase and it's a bit different than the one outlined in the PR. Here's the code snippet, I'm doing it in the data provider as a custom build query:

```
const customBuildQuery = introspection => (fetchType, resource, params) => {
const builtQuery = buildQuery(introspection)(fetchType, resource, params);

if (fetchType === 'GET_MANY_REFERENCE') {
		// Targeting this weird bug: https://github.com/marmelab/react-admin/issues/2571
		// Hopefully this gets fixed soon.
		for (let filterOpt in builtQuery.variables.filter) {
			if (
				typeof builtQuery.variables.filter[filterOpt] === 'object' &&
				filterOpt.includes("Id") &&
				builtQuery.variables.filter[filterOpt].id
			) {
				builtQuery.variables.filter[filterOpt] = builtQuery.variables.filter[filterOpt].id
			}
		}
	}
	return builtQuery;
}
```

It's probably overly targeted, but we wanted to be safe without digging really deep into the codebase. Do you know where the equivalent would be? I think it should be just something as simple as:

```
case GET_MANY_REFERENCE: {
    const parts = params.target.split('.');
    return filter: { [parts[0]]: params.id };
}
```

I won't be near my main computer though for a few more days.

**Comment by Redorb** [comment]
Alright after looking through the rest of the code in this area it makes sense. Not sure how the code in that issue worked for the OP though. I amended the commit with something similar to what I'm doing in my workaround, let me know if I need to update anything else.

**Comment by christiaanwesterbeek** [comment]
I encountered the same problem and fixed it according to this PR. I vote to re-open and merge this PR.

**Comment by djhi** [comment]
I don't know why @redorb closed this PR

**Comment by redorb** [comment]
I can't remember why I ended up closing it. Feel free to look through the PR if it's still in need of a fix.

**Comment by redorb** [comment]
Merged master into the branch, sorry if anything is weird. I'm doing these edits in the github UI since I'm not going to be near my laptop for a month or so.

**Pull request merged**
