### PR TITLE
[ra-input-rich-text] rerender component on input change

### LINKED ISSUE #3206: [ra-input-rich-text] validation doesn't rerun on input change
**What you were expecting:**

I expect no validation error when required rich text input has content

**What happened instead:**

Validation error persists, even when input is not empty anymore

**Steps to reproduce:**

1. Run simple example
2. Go to PostCreate.js
3. Add `validate={[required()]}` to `RichTextInput`
4. Try to edit rich text input

**Other information:**

Screen-Recording-2019-05-09-at-15 47 35

Looking at source code, there's `shouldComponentUpdate` method:

https://github.com/marmelab/react-admin/blob/cd560cb9ba6f78efd098449e5e3febcf26418f25/packages/ra-input-rich-text/src/index.js#L61-L63

But when it executes, both values are the same, therefore component doesn't rerender:

Screenshot 2019-05-09 at 15 59 14

**Environment**

* React-admin version: 2.9.0
* ra-input-rich-text version: 2.8.6
* Last version that did not exhibit the issue (if applicable): N/A
* React version: N/A
* Browser: N/A
* Stack trace (in case of a JS error): N/A

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes #3206

### CODE REVIEW

**Comment by cherniavskii** [comment]
I've also fixed an issue, when after pressing submit button rich text input error message is not visible.
This was due to `shouldComponentUpdate`, which allowed rerenders only when input value changes.

**Comment by cherniavskii** [comment]
Basically, `shouldComponentUpdate` blocks rerenders to avoid firing `componentDidUpdate` side effect. It works, but with a drawback - component doesn't rerender on other props change (e.g. `meta`)

This PR removes render blocking. Instead, it blocks unnecessary `componentDidUpdate` side effect invocations.

**Comment by fzaninotto** [comment]
Not good: this patch breaks the storage of the rich text value. I create a post, add a body, save the post, then check the body, and the test I typed isn't there. 

I can't merge this one, and I'll have to rollback #3208, too, since it breaks another feature.

If you want your patches to be accepted, please test thoroughly, and even better, please add automated tests.

**Comment by cherniavskii** [comment]
Hi @fzaninotto 
Looks like there's misunderstanding here.
The issue you're talking about is currently reproducible on master (see GIF from master below).
It is caused by wrong debouncing handling, which also causes #3220
I'll address it in separate PR, which I'm working on right now.

j9smk-4p29i

Would you reconsider merging this PR as well as reverted #3208 ?
Those are fixing two bugs, an do not introduce any regressions

**Comment by cherniavskii** [comment]
@fzaninotto do you mean unit or integration tests? Which cases should be covered?

**Comment by fzaninotto** [comment]
unit when you can, but I believe mostly integration and e2e tests because we're speaking about problems following navigation. 

Please cover the cases of the bugs you're trying to fix. I'll add the normal cases.

**Comment by cherniavskii** [comment]
@fzaninotto sure, I'll open another PR then

**Comment by fzaninotto** [comment]
Superseded by #3223

**Pull request closed without merging**
