### PR TITLE
Data-driven

### PR DESCRIPTION
**Pull request by christiaanwesterbeek**
I would use react-admin not just for B2B (as your Github repo description says) or admin applications. But for any data-driven web application that I would start or plan to build today.

### CODE REVIEW

**Comment by fzaninotto** [comment]
I'm not sure this is better. What's a non data-driven application?

**Comment by christiaanwesterbeek** [comment]
Yeah, I'm not sure either. I read "B2B" on the github repo description and "admin" in readme. I've built a react-admin based application that looks nothing like admin and nothing like react-admin, and is used by thousands of consumers daily. I was looking for something that they have in common. I couldn't come up with anything else than data-driven.

**Comment by fzaninotto** [comment]
Well, as we already say "admin" in the library title, we can afford using another buzzword in the description. Thanks for the PR.

On another subject, are you authorized to mention the app you've built with react-admin in #4027?

**Comment by christiaanwesterbeek** [comment]
I will ask if it's OK if I write something in #4027 

Another idea. Maybe you could go for data-centric, because indeed what isn't data-driven these days, but react-admin does focus and shine on working with data.

**Pull request merged**
