### PR TITLE
[WIP] makeStyles and functional components

### PR DESCRIPTION
**Pull request by MohammedFaragallah**
Refs #3453

current status

* [x]  `examples/demo/src/layout/Login.js`
* [ ]  `ra-input-rich-text/src/index.js`
* [x]  `ra-tree-ui-materialui/src/DragLayer.js`
* [x]  `ra-tree-ui-materialui/src/DragPreview.js`
* [x]  `ra-tree-ui-materialui/src/NodeActions.js`
* [x]  `ra-tree-ui-materialui/src/NodeForm.js`
* [x]  `ra-tree-ui-materialui/src/NodeView.js`
* [x]  `ra-tree-ui-materialui/src/RootDropTarget.js`
* [x]  `ra-tree-ui-materialui/src/Tree.js`
* [x]  `ra-tree-ui-materialui/src/TreeNode.js`
* [x]  `ra-ui-materialui/src/Link.tsx`
* [ ]  `ra-ui-materialui/src/auth/Login.tsx`
* [x]  `ra-ui-materialui/src/auth/LoginForm.tsx`
* [x]  `ra-ui-materialui/src/button/CreateButton.js`
* [x]  `ra-ui-materialui/src/button/SaveButton.js`
* [x]  `ra-ui-materialui/src/field/BooleanField.tsx`
* [x]  `ra-ui-materialui/src/field/ChipField.tsx`
* [x]  `ra-ui-materialui/src/field/FileField.tsx`
* [x]  `ra-ui-materialui/src/field/ImageField.tsx`
* [x]  `ra-ui-materialui/src/form/FormInput.js`
* [x]  `ra-ui-materialui/src/form/SimpleFormIterator.js`
* [x]  `ra-ui-materialui/src/form/TabbedForm.js`
* [x]  `ra-ui-materialui/src/form/Toolbar.js`
* [ ]  `ra-ui-materialui/src/input/AutocompleteArrayInput.js`
* [x]  `ra-ui-materialui/src/input/AutocompleteArrayInputChip.js`
* [ ]  `ra-ui-materialui/src/input/AutocompleteInput.js`
* [x]  `ra-ui-materialui/src/input/CheckboxGroupInput.js`
* [ ]  `ra-ui-materialui/src/input/FileInput.js`
* [x]  `ra-ui-materialui/src/input/FileInputPreview.js`
* [ ]  `ra-ui-materialui/src/input/ImageInput.js`
* [x]  `ra-ui-materialui/src/input/Labeled.js`
* [ ]  `ra-ui-materialui/src/input/NullableBooleanInput.js`
* [x]  `ra-ui-materialui/src/input/RadioButtonGroupInput.js`
* [x]  `ra-ui-materialui/src/input/ResettableTextField.js`
* [x]  `ra-ui-materialui/src/input/SearchInput.js`
* [ ]  `ra-ui-materialui/src/input/SelectArrayInput.js`
* [x]  `ra-ui-materialui/src/input/SelectInput.js`
* [x]  `ra-ui-materialui/src/layout/AppBar.js`
* [x]  `ra-ui-materialui/src/layout/CardContentInner.js`
* [x]  `ra-ui-materialui/src/layout/Confirm.js`
* [x]  `ra-ui-materialui/src/layout/Error.js`
* [ ]  `ra-ui-materialui/src/layout/Layout.js`
* [x]  `ra-ui-materialui/src/layout/LinearProgress.js`
* [x]  `ra-ui-materialui/src/layout/Loading.js`
* [x]  `ra-ui-materialui/src/layout/LoadingIndicator.js`
* [x]  `ra-ui-materialui/src/layout/Menu.js`
* [x]  `ra-ui-materialui/src/layout/MenuItemLink.js`
* [x]  `ra-ui-materialui/src/layout/NotFound.js`
* [ ]  `ra-ui-materialui/src/layout/Notification.js`
* [x]  `ra-ui-materialui/src/layout/Sidebar.js`
* [ ]  `ra-ui-materialui/src/list/BulkActions.js`
* [x]  `ra-ui-materialui/src/list/BulkActionsToolbar.js`
* [x]  `ra-ui-materialui/src/list/Datagrid.js`
* [x]  `ra-ui-materialui/src/list/DatagridHeaderCell.js`
* [x]  `ra-ui-materialui/src/list/DatagridLoading.js`
* [x]  `ra-ui-materialui/src/list/Filter.js`
* [x]  `ra-ui-materialui/src/list/FilterButton.js`
* [x]  `ra-ui-materialui/src/list/FilterForm.js`
* [x]  `ra-ui-materialui/src/list/PaginationActions.js`
* [x]  `ra-ui-materialui/src/list/SimpleList.js`
* [x]  `ra-ui-materialui/src/list/SingleFieldList.js`

And then there is the doc:

* [x]  `CreateEdit.md`
* [x]  `Fields.md`
* [ ]  `List.md`
* [ ]  `Theming.md`
* [x]  `Tutorial.md`

### CODE REVIEW

**Comment by MohammedFaragallah** [comment]
@djhi sorry but how to continue adding changes to this pull request i don't fully understand this workflow yet

**Comment by Kmaschta** [comment]
Ah! The tests are failing because with the `withStyles` HOC, the components were wrapped on the tests like `WithStyles(Component)`.

This is no longer the case now with the hook.
Can you remove all the `WithStyles(x)` and only keep the `x` in the tests that are failing?

**Comment by djhi** [comment]
> Can you remove all the WithStyles(x) and only keep the x in the tests that are failing?

Even better, if you feel up for it, convert them to `react-testing-library` :heart_eyes:

**Comment by MohammedFaragallah** [comment]
> Even better, if you feel up for it, convert them to `react-testing-library` 😍

sorry @djhi i don't think i can do this i'm not very good with testing

**Comment by Kmaschta** [comment]
This looks very good to me.
But don't bother transforming class-based components into function-based ones.

You can use `useStyles` in a `render()` function of a class-based component.
That way, you can let all the lifecycle in place.

**Comment by djhi** [comment]
> You can use `useStyles` in a `render()` function of a class-based component.

No, `useStyles` is a hook. Hooks cant' be used in a class component

**Comment by Kmaschta** [comment]
My bad! Seems like we can't. https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both

So, about your question, you can use `React.memo` instead of `shouldComponentUpdate`: https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-shouldcomponentupdate

**Comment by MohammedFaragallah** [comment]
@djhi some components are class based while they dot use any lifecycle methods or internal state like ra-tree-ui-materialui/TreeNodeContent should i convert them too ?

and could you give savebutton tests a look

**Comment by Kmaschta** [comment]
If you feel like you can convert them, else you don't have to.
We'll just mark them as non-converted, it's ok.

**Comment by MohammedFaragallah** [comment]
It's fine by me i would love to help this awesome project whenever i can

**Comment by MohammedFaragallah** [comment]
current status

> * [x]  `examples/demo/src/layout/Login.js`
> * [ ]  `ra-input-rich-text/src/index.js`
> * [x]  `ra-tree-ui-materialui/src/DragLayer.js`
> * [x]  `ra-tree-ui-materialui/src/DragPreview.js`
> * [x]  `ra-tree-ui-materialui/src/NodeActions.js`
> * [x]  `ra-tree-ui-materialui/src/NodeForm.js`
> * [x]  `ra-tree-ui-materialui/src/NodeView.js`
> * [x]  `ra-tree-ui-materialui/src/RootDropTarget.js`
> * [x]  `ra-tree-ui-materialui/src/Tree.js`
> * [x]  `ra-tree-ui-materialui/src/TreeNode.js`
> * [x]  `ra-ui-materialui/src/Link.tsx`
> * [ ]  `ra-ui-materialui/src/auth/Login.tsx`
> * [x]  `ra-ui-materialui/src/auth/LoginForm.tsx`
> * [x]  `ra-ui-materialui/src/button/CreateButton.js`
> * [x]  `ra-ui-materialui/src/button/SaveButton.js`
> * [x]  `ra-ui-materialui/src/field/BooleanField.tsx`
> * [x]  `ra-ui-materialui/src/field/ChipField.tsx`
> * [x]  `ra-ui-materialui/src/field/FileField.tsx`
> * [x]  `ra-ui-materialui/src/field/ImageField.tsx`
> * [x]  `ra-ui-materialui/src/form/FormInput.js`
> * [x]  `ra-ui-materialui/src/form/SimpleFormIterator.js`
> * [x]  `ra-ui-materialui/src/form/TabbedForm.js`
> * [x]  `ra-ui-materialui/src/form/Toolbar.js`
> * [ ]  `ra-ui-materialui/src/input/AutocompleteArrayInput.js`
> * [x]  `ra-ui-materialui/src/input/AutocompleteArrayInputChip.js`
> * [ ]  `ra-ui-materialui/src/input/AutocompleteInput.js`
> * [x]  `ra-ui-materialui/src/input/CheckboxGroupInput.js`
> * [ ]  `ra-ui-materialui/src/input/FileInput.js`
> * [x]  `ra-ui-materialui/src/input/FileInputPreview.js`
> * [ ]  `ra-ui-materialui/src/input/ImageInput.js`
> * [x]  `ra-ui-materialui/src/input/Labeled.js`
> * [ ]  `ra-ui-materialui/src/input/NullableBooleanInput.js`
> * [x]  `ra-ui-materialui/src/input/RadioButtonGroupInput.js`
> * [x]  `ra-ui-materialui/src/input/ResettableTextField.js`
> * [x]  `ra-ui-materialui/src/input/SearchInput.js`
> * [ ]  `ra-ui-materialui/src/input/SelectArrayInput.js`
> * [x]  `ra-ui-materialui/src/input/SelectInput.js`
> * [x]  `ra-ui-materialui/src/layout/AppBar.js`
> * [x]  `ra-ui-materialui/src/layout/CardContentInner.js`
> * [x]  `ra-ui-materialui/src/layout/Confirm.js`
> * [x]  `ra-ui-materialui/src/layout/Error.js`
> * [ ]  `ra-ui-materialui/src/layout/Layout.js`
> * [x]  `ra-ui-materialui/src/layout/LinearProgress.js`
> * [x]  `ra-ui-materialui/src/layout/Loading.js`
> * [x]  `ra-ui-materialui/src/layout/LoadingIndicator.js`
> * [x]  `ra-ui-materialui/src/layout/Menu.js`
> * [x]  `ra-ui-materialui/src/layout/MenuItemLink.js`
> * [x]  `ra-ui-materialui/src/layout/NotFound.js`
> * [ ]  `ra-ui-materialui/src/layout/Notification.js`
> * [x]  `ra-ui-materialui/src/layout/Sidebar.js`
> * [ ]  `ra-ui-materialui/src/list/BulkActions.js`
> * [x]  `ra-ui-materialui/src/list/BulkActionsToolbar.js`
> * [x]  `ra-ui-materialui/src/list/Datagrid.js`
> * [x]  `ra-ui-materialui/src/list/DatagridHeaderCell.js`
> * [x]  `ra-ui-materialui/src/list/DatagridLoading.js`
> * [x]  `ra-ui-materialui/src/list/Filter.js`
> * [x]  `ra-ui-materialui/src/list/FilterButton.js`
> * [x]  `ra-ui-materialui/src/list/FilterForm.js`
> * [x]  `ra-ui-materialui/src/list/PaginationActions.js`
> * [x]  `ra-ui-materialui/src/list/SimpleList.js`
> * [x]  `ra-ui-materialui/src/list/SingleFieldList.js`
> 
> And then there is the doc:
> 
> * [x]  `CreateEdit.md`
> * [x]  `Fields.md`
> * [ ]  `List.md`
> * [ ]  `Theming.md`
> * [x]  `Tutorial.md`

**Comment by Kmaschta** [comment]
Don't feel obligated to migrate all the components at once!
The smaller the PR is, the faster it will be reviewed and merged.
The bigger it is, the more you might get rebase to do and request changes.

This one tend to be huge, and a split might be a good idea IMHO.

**Comment by fzaninotto** [comment]
@MohammedFaragallah please fix the tests before converting more components. We can't marge this PRs if it breaks the tests.

**Comment by MohammedFaragallah** [comment]
@Kmaschta yes i won't be converting any more components this status list is for the maintainers to keep track whats almost done, but i'll focus on getting tests fixed as @fzaninotto asked, sorry for the delay but i'm really busy this days and my lack of experience with testing isn't helping very soon all will be resolved i hope

**Comment by djhi** [comment]
@MohammedFaragallah I'm going to change all inputs for react-final-form migration. I will update them to use `makeStyle` at the same time. You should omit them to avoid conflicts later in your smaller prs

**Comment by Kunnu01** [comment]
@djhi , What to do in case of `componentDidCatch`?

**Comment by fzaninotto** [comment]
Thanks a lot for your effort, but your work isn't going to be merged soon, because of the rebases and failed tests. I'm going to close this, and I recommend that you cherry-pick the commits to open smaller PRs, migrating a handful of components only (less than a dozen), and making sure the tests pass. I'll do the same for your other PR.

**Pull request closed without merging**
