### PR TITLE
[DX] Thrown an error when using a Reference field without the associated Resource

### LINKED ISSUE #6258: Thrown an error when using a Reference field without the associated Resource
Many newcomers don't understand why their ReferenceField or referenceManyField doesn't display anything - generally, they have forgotten to declare the related Resource. 

It's documented, but many newcomers don't read the documentation.

We can detect that such components are used without the right resource, we should throw an explicit error in that case.

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #6258

### CODE REVIEW

**Review by djhi — APPROVED** [review]

**Review by djhi — COMMENTED** [review]
Why is targeting the `next` branch?

**Comment by fzaninotto** [comment]
Because it's not a bug fix.

**Comment by djhi** [comment]
Right but it does not really add any feature, right?

**Comment by fzaninotto** [comment]
Right, but a bugfix release can only contain bug fixes, so...

**Pull request merged**
