### PR TITLE
[Doc] Update `useUpdate` doc to explain `returnPromise` option

### PR DESCRIPTION
**Pull request by fzaninotto**

### CODE REVIEW

**Review by djhi — COMMENTED** [review]
I know we have many such examples, but shouldn't we make them closer to real world usage (inside a custom button, etc)?

**Comment by fzaninotto** [comment]
> I know we have many such examples, but shouldn't we make them closer to real world usage (inside a custom button, etc)?

This is the closest to real world usage I could find.

**Comment by djhi** [comment]
> > I know we have many such examples, but shouldn't we make them closer to real world usage (inside a custom button, etc)?
> 
> This is the closest to real world usage I could find.

I meant have a real button with JSX and imports

**Comment by fzaninotto** [comment]
> > > I know we have many such examples, but shouldn't we make them closer to real world usage (inside a custom button, etc)?
> > 
> > 
> > This is the closest to real world usage I could find.
> 
> I meant have a real button with JSX and imports

IMHO it dilutes the example. In addition, we don't do it for the other options.

**Pull request merged**
