### PR TITLE
Add InputLabelProps and formHelperTextProps props

### LINKED ISSUE #7386: Allow for passing FormHelperTextProps and InputLabelProps to SelectArrayInput
Currently the [SelectArrayInput](https://github.com/marmelab/react-admin/blob/dfcd326eafb59bbd4fa777a4e8a003a928c36ce2/packages/ra-ui-materialui/src/input/SelectArrayInput.tsx#L221L281) component does not allow for passing **label props** and **helper text props**. Any props passed that aren't removed after sanitization are only applied to the `<FormControl />` component. This seems like very odd behavior as other react-admin inputs accept those props and are passed down to the underlying Material UI components. The same should apply to SelectArrayInput, ArrayInput, BooleanInput and NullableBooleanInput, etc. 

**Solution**
* Allow for **label props** to be passed to the <InputLabel /> component. Example: [SelectArrayInput](https://github.com/marmelab/react-admin/blob/dfcd326eafb59bbd4fa777a4e8a003a928c36ce2/packages/ra-ui-materialui/src/input/SelectArrayInput.tsx#L228L239).
```JS
<InputLabel
    ref={inputLabel}
    id={`${label}-outlined-label`}
    error={touched && !!(error || submitError)}
    {...InputLabelProps}
>
    <FieldTitle
        label={label}
        source={source}
        resource={resource}
        isRequired={isRequired}
    />
</InputLabel>
```

* Allow for form **helper text props** to be passed to the `<FormHelperText />` component. Example: [SelectArrayInput](https://github.com/marmelab/react-admin/blob/dfcd326eafb59bbd4fa777a4e8a003a928c36ce2/packages/ra-ui-materialui/src/input/SelectArrayInput.tsx#L273L279).
```JS
<FormHelperText error={touched && !!(error || submitError)} {...FormHelperTextProps}>
    <InputHelperText
        touched={touched}
        error={error || submitError}
        helperText={helperText}
    />
</FormHelperText>
```

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #7386

### CODE REVIEW

**Comment by WiXSL** [comment]
> Besides, I believe we also don't provide those props for many of the other inputs

You are right

**Comment by mccasey** [comment]
Seems this pr was closed due to those props not being provided to many other inputs. This seems like an odd reason to close this pr. This type of inconsistency between inputs should be addressed. If some inputs allow for passing label and helper text props to the underlying MUI component then all inputs should.

**Comment by djhi** [comment]
Thanks for your input. Would you open a PR for that?

**Comment by mccasey** [comment]
Sure. I'll see if I can start on this work this upcoming weekend.

**Pull request closed without merging**
