### PR TITLE
Fix the Refresh of Lists when an optimistic update fails

### LINKED ISSUE #4176: List does not refresh after API error (video included)
After the "Save" returns an API error, the rejected value is reverted in the List

The API returned error and the List still shows the rejected value.

Video below.

**Environment**

* React-admin version: 3.0.3
* React version: 16.12
* Browser: Chrome 78

React Admin 2.9
ezgif-ra29

React Admin 3.0
ezgif-ra30

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #4176

### CODE REVIEW

**Comment by fzaninotto** [comment]
You must also remove the call to the `refresh()` side effect in `useEditController` and `useShowController`, otherwise the refresh will occur twice.

**Comment by m4theushw** [comment]
@fzaninotto I'm calling `refresh` only on undoable operations. I think that is not the case of `useEditController` and `useShowController` since they refresh when `getOne` fails. Am I right?

**Comment by fzaninotto** [comment]
Right, but then with your patch there will still be two refreshes in case of optimistic error. 

So the right way to fix this bug is to add a refresh as onFailure side effect in the save function of useEditController and useCreateController.

**Comment by m4theushw** [comment]
I didn't add a refresh in `useCreateController` because it's not undoable and this bug only occurs with optimistic saving.

**Comment by JulienMattiussi** [comment]
Closes #3244

**Comment by fzaninotto** [comment]
Thanks!

**Comment by fzaninotto** [comment]
hm, this PR, once merged to master, breaks the e2e tests. I'll take a look.

**Comment by fzaninotto** [comment]
Fixed in b23212028eb975edcf9e7e6caadfdc17bf874c66

**Pull request merged**
