### PR TITLE
[RFR] Add datepicker component

### PR DESCRIPTION
**Pull request by manuquentin**
- [x] Add datepicker
- [x] Add tests

Tests will pass after the merge of [admin-config#15](https://github.com/marmelab/admin-config/pull/15).

capture d ecran 2015-06-16 a 15 43 41

### CODE REVIEW

**Comment by jeromemacias** [comment]
Test failed

**Comment by manuquentin** [comment]
Have you read the description ? :)

**Comment by jeromemacias** [comment]
No, I don't, sorry.
Pr on ng-admin had been merged.

**Comment by jeromemacias** [comment]
I've juste [update](https://github.com/marmelab/react-admin/commit/0b28a47ef3ea5717d4457a5fdc164808c9c7dcd0) `admin-config` dependency to latest version, can you rebase please ?

**Pull request merged**
