### PR TITLE
[RFR] Allow aliases in graphql dataprovider

### PR DESCRIPTION
**Pull request by Oupsla**
Fix: https://github.com/marmelab/react-admin/issues/3160

### CODE REVIEW

**Comment by Oupsla** [comment]
Hello @fzaninotto,
Could be possible to get a review ? 😄

**Comment by djhi** [comment]
Thanks for working on this! It looks good to me. I'll have to test it against the demo though and I won't be able to do so before monday. It would be great to find a usecase for aliases in the demo too. I'll try to figure something but go ahead if you think of something first.

**Comment by Oupsla** [comment]
I encounter this need for a specific problem at work 😄 

My usecase is that I got users and organisations (and those organisations got accesses to 'things' ).

So in a show view I have created tabs to show the summary of the user, his organisations and his accesses (through his organisations).

So I got a query like that (to fetch one user) (little note, I follow recommandations of graphql for paginations between object) : 
```gql

query User($id: ID!) {
    data: User(id: $id) {
      id
      email
      organisations: organisationsConnection(first: 100) {
        edges {
          id
          type
          node {
            id
            name
            identification
          }
        }
      }
accesses: organisationsConnection(first: 100) {
        edges {
          node {
            accessesConnection(first: 100) {
              edges {
                node {
                  id
                  name
                }
              }
            }
          }
        }
      }
    }
  }
```

So I need to query the same subquery 2 times (and so the need of aliases 😄 ).

**Comment by djhi** [comment]
Thanks for sharing. I was looking for a use case in our demo example though :)

**Comment by Oupsla** [comment]
Don't merge it right now, I have detected an issue while using it !
If the same alias is used multiple times but at different levels of the graphql query, it can fails... (it is a edge case but I have encounter it 😄 ), I'll try to fix it and commit it

**Comment by Oupsla** [comment]
After working on a solution, I was wondering the goal of the method `sanitizeResource`.
I tried to removing it completely and my project is working (and with aliases 😆 ) .

@djhi (or maybe @fzaninotto), do you have more insights about this method ? (It is maybe a legacy that can be removed).

**Comment by Oupsla** [comment]
I have tried another approach, not based on graphql introspection that just filter the response and add things (like `.id` and `Ids`, based on tests).
This solution allows aliases.

I think it is better cause the response payload of a graphql endpoint must respect the query so no need to check the introspection.

Already tested through my project (with aliases) and working, tell me what you think about it 😄

**Comment by Oupsla** [comment]
@djhi @fzaninotto Friendly ping to get a review if you got time 😄

**Comment by Oupsla** [comment]
Hello folks !
Any news about reviewing/merging this PR ?

**Comment by djhi** [comment]
Sorry about that. We've been very busy working on the v3. As this is a new feature, would you mind targeting the `next` branch ? I'll take a look right after!

**Comment by Oupsla** [comment]
No problem, base PR changed and rebased. Just wanted to do a friendly ping so this PR don't die 😄 
By the way really good work for the v3, really eager to try it out !

**Comment by djhi** [comment]
Thanks!

**Pull request merged**
