### PR TITLE
Adds Spanish language package

### PR DESCRIPTION
**Pull request by alfonsodev**
Hola,
I've made the translation for Spanish messages, I'm not sure if you would like to have the package merged in the main repo, or otherwise you prefer it to be in a separate repository.  

If you know Spanish maybe you can review and give your opinion, perhaps people from south America would use different words, I'm open to find synonyms  that work best for all of us.   
I found some expressions are hard to translate for example . 
```
            clear_input_value: 'Despejar valor',
```
I'm pretty sure there is better way to express that, perhaps "limpiar valor" ?, "restablecer valor" ?
and I'm ignoring "input" there because it sounds weird "limpiar valor de entrada" but you might think otherwise.   
Let me know your opinion.  
Thanks.

### CODE REVIEW

**Comment by djhi** [comment]
Thanks! We won't be able to maintain this translation. Can you publish it as a stand-alone package ?

**Comment by alfonsodev** [comment]
Thank for the quick reply, I'll publish it separately.

**Comment by djhi** [comment]
Btw, are you aware of the existing spanish translation package https://github.com/BlackBoxVision/ra-language-spanish?

It is already on our official list https://marmelab.com/react-admin/Translation.html#available-locales

**Comment by alfonsodev** [comment]
yes, I saw it after translating it, I've checked now, but it is not updated, I'll try to make a pull request there to update it or in case there is no answer I'll point here to mine too.

**Pull request closed without merging**
