### PR TITLE
Fix pagination buttons are in the wrong direction in RTL languages

### PR DESCRIPTION
**Pull request by alikazemkhanloo**
this PR will change the chevron direction in PaginationActrions for RTL, as in the gist suggested in #3348. But using hooks to get the theme.

### CODE REVIEW

**Comment by fzaninotto** [comment]
I'm not sure I understand. Can you please explain the problem, and paste a screenshot to show the result of your change?

**Comment by kopax** [comment]
RTL means right to left, such as arabic language. 
image

**Comment by fzaninotto** [comment]
I know that, I just don't understand what the problem is with pagination in RTL languages.

**Comment by alikazemkhanloo** [comment]
this is what it looks like in RTL:

Screenshot from 2020-03-10 12-55-29---

**Comment by JulienMattiussi** [comment]
@alikazemkhanloo 
I think your reverted ChevronLeft and ChevronRight in your PR, because you keep the current behaviour when `direction === rtl`.

**Comment by alikazemkhanloo** [comment]
@JulienMattiussi Thanks.

**Comment by fzaninotto** [comment]
thanks!

**Pull request merged**
