### PR TITLE
[RFR] Move Actions out of the Card

### PR DESCRIPTION
**Pull request by fzaninotto**
- [x] Move ListActions out of the card
- [x] Make BulkActions stand out of the card
- [x] Move EditActions out of the card
- [x] Move ShowActions out of the card
- [x] Move CreateActions out of the card
- [x] [BC Break] Remove CardActions component (replaced by TopToolbar)
- [x] Update documentation and examples
- [x] Put white background behind actions on Mobile

ezgif com-video-to-gif (2)

Note that the change moves the content *up* in the list but *down* in the Edit view (when there are buttons), but the buttons and cards are aligned across views.

|Page|Before|After|
|-------|---------|------|
|List | localhost_8080_ (6) | localhost_8080_ (1) | 
|Edit |localhost_8080_ (3)|localhost_8080_|
|Show|localhost_8080_ (4)|localhost_8080_ (1)|
|Create|localhost_8080_ (5)|localhost_8080_ (2)|

### CODE REVIEW

**Comment by djhi** [comment]
Looks great !

**Comment by djhi** [comment]
Wold you mind posting screenshots of the mobile view ?

**Comment by fzaninotto** [comment]
| | | |
|-|-|-|
| localhost_8080_ (3) | localhost_8080_ (2) | localhost_8080_ (4) |

the last one has a width problem, which also exists in the current UI. It's due to the tabs not being responsive enough (that's a known material-ui bug).

**Comment by serhiipalash** [comment]
Looks great @fzaninotto ! When will you plan to release v3?

**Comment by fzaninotto** [comment]
see #3194

**Pull request merged**
