### PR TITLE
Added in ability to create custom parameters

### PR DESCRIPTION
**Pull request by yashaRO**
customParameters option should take in a function.
In that function, you can do w/e with the provided data and return an object mirroring the params argument.

```javascript
console.log(params)
/*
{
     data: {someData},
     previousData: {someData},
     id
}
*/
```

```javascript
console.log(customParams)
/*
{
     data: {modifiedData},
     previousData: {someData},
     id
}
*/
```

### CODE REVIEW

**Comment by djhi** [comment]
Can you describe your use case ?

**Comment by fzaninotto** [comment]
@djhi he did in #1837

**Comment by djhi** [comment]
I think this is achievable without modifying this package at all:

```js
import buildGraphQLProvider from 'ra-data-graphql-simple';

export default options =>
    buildGraphQLProvider(options)
        .then(defaultDataProvider =>
            (fetchType, resource, params) => {
                // By default, use the params we received
                let finalParams = params;

                // Check your conditions for custom handling
                if (...) {
                    // Custom handling
                    const newParams = {};

                    // Apply custom handling results
                    finalParams = myNewParams;
                }

                return defaultDataProvider(fetchType, resource, finalParams);
            });
```

**Comment by djhi** [comment]
@yashaRO Can you please confirm that this wrapper approach resolves your issue ?

**Comment by yashaRO** [comment]
@djhi Yeah that works

**Pull request closed without merging**
