### PR TITLE
ReferenceField: show linearProgress bar only if some data are fetched

### PR DESCRIPTION
**Pull request by sebastien-cleany**
The linearProgress bar was displayed whereas there was no data to fetch.
Thus the bar was displayed for ever. The only way to not have the
progress bar forever, was to set allowEmpty to true.
However, this was removing completely the waiting bar.
And this is not a good idea, because users will not see that data are loading.

So now, if allowEmpty is set, linearProgress is shown while the data
are loaded, and if there is no data to fetch the bar is hidden.

The behavior is not changed if allowEmpty is not set.

### CODE REVIEW

**Comment by fzaninotto** [comment]
I don't understand the rationale. If the field isn't nullable, then the absence of reference in the `render()` function means that it's being fetched, thus showing the download bar makes sense. That's what was implemented previously. Your patch breaks that. 

If the field is nullable, you have to use `allowEmpty: true`. Or am I missing something?

**Comment by alexeyoganezov** [comment]
I confirm the problem, "linear progress" has strange behavior right now.

> If the field is nullable, you have to use allowEmpty: true. Or am I missing something?
In that case "linear progress" component doesn't  show up at all, so users don't know if value is still loading or it's already loaded and equal "null".

**Comment by fzaninotto** [comment]
Right, using `allowEmpty` here is wrong. But your patch is wrong, too.

Here is the rationale:

1. if the source is null, display nothing. We don't even call `fetchReference()` in that case, there is nothing to fetch.
2. if the source is not null, and the referenceRecord is null, it means that:
    a. it's loading, so display loading, or
    b. it's a reference to a non existing record (not supported so far), so display nothing
3. if the referenceRecord is not null, render the child component with it

How do we tell 2a from 2b? It's impossible with the current code. What we need to do is to change the default value of `referenceValue` to `false` instead of `null`. That way you can write the following algorithm:

- if the source is null, display nothing, else
- switch referenceRecord
  - case false, display `<Loading>`
  - case null, display nothing
  - case not null, render the child component with it

Do you agree?

**Comment by djhi** [comment]
> What we need to do is to change the default value of referenceValue to false instead of null.

That won't work. If `mapStateToProps` returns `null` after fetching the reference, we'll get the default prop `false`.

**Comment by djhi** [comment]
The only way I can think of to fix this would be to store the fetching state in the redux store for every record. That means creating a record entry whenever asking for one with two properties: `value` and `fetched`.

**Comment by fzaninotto** [comment]
Other solution: map the loading state to a component prop. When something is loading and the `referenceRecord` is null, show the loader. When nothing is loading, hide the loader.

This will look less performant than the current setting (where the loaders disappear one by one as the responses arrive), but solve the problem in a simple way.

**Comment by fzaninotto** [comment]
Any update on this one?

**Pull request closed without merging**
