### PR TITLE
[Doc] Convert GIF files to WebM

### PR DESCRIPTION
**Pull request by slax57**
Convert GIF files to WebM to reduce assets size.
Total GIF files size: **44.9 MiB**
Total WebM files size: **16.9 MiB**
Reduced assets size by **62.41 %**!

## Todo

- [x] Discuss if we should keep the GIF files for now or not
- [x] Fix `TimeInput.md`
- [x] Needs more testing
- [x] Improve video quality
- [x] Use CSS instead of repeating the styles
- [x] Fine-tune the video quality to better optimize assets size

### CODE REVIEW

**Comment by fzaninotto** [comment]
Great! But the compression is a bit too aggressive, and artifacts are visible. 

I tested on the [features page](https://marmelab.com/react-admin/Features.html#search--filtering), mostly the saved queries gif.

**Review by djhi — CHANGES_REQUESTED** [review]

**Comment by fzaninotto** [comment]
needs rebase

**Comment by slax57** [comment]
I've updated the WebM files with the following changes:
- CRF set to 24
- Maximum FPS set to 15
- Maximum video resolution set to 1920x1080

With these changes, the assets size was reduced by 62.41 %, hopefully with not too much impact on quality :slightly_smiling_face:

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Awesome!

**Pull request merged**
