### PR TITLE
Fix ra-data-graphql-simple UPDATE_MANY incorrect build variable {data} 

### LINKED ISSUE #2776: ra-data-graphql-simple UPDATE_MANY incorrect build variable {data}
**What you were expecting:**
When creating the BulkArchiveButton, I expected correct execution mutation

**What happened instead:**
UPDATE_MANY a few times causes the execution of the UPDATE
the required ID argument is not passed to the {data} parameter

**Steps to reproduce:**
try to update any resource through the CustomBulkActionButton

**Other information:**
Wrote the BulkArchiveButton as in the example in the documentation:

```
class BulkArchiveButton extends Component {
    handleArchive = () => {
        const {  basePath, resource, selectedIds, startUndoable } = this.props;
        startUndoable(
            crudUpdateMany(resource, selectedIds, { isArchved: true }, basePath)
        );
    };
    render() {
        const { className, classes, filterValues } = this.props;
        return (
            <Button 
                size="small"
                variant="outlined"
                label="raExt.action.archive"
                onClick={this.handleArchive}
                className={`${classes.button} ${classes.archiveButton} ${className}`}
            >
                <ArchiveIcon />
            </Button>
        );
    }
}
```

This is the request this button sends:
default

That's what gets a response:
default

To solve the problem fixed 

> C:\...\ui-react-admin\node_modules\ra-data-graphql-simple\esm\index.js

```
...
               if (fetchType === UPDATE_MANY) {
                var ids = params.ids, otherParams_2 = __rest(params, ["ids"]);
                return Promise.all(params.ids.map(function (id) {
                    
                 //return defaultDataProvider(UPDATE, resource, __assign({ id: id }, otherParams_2));
                    return defaultDataProvider(UPDATE, resource, {data:__assign({ id: id }, otherParams_2.data)});

                })).then(function (results) {
                    var data = results.reduce(function (acc, _a) {
                        var data = _a.data;
                        return acc.concat([data.id]);
                    }, []);
                    return { data: data };
                });
            }
...
```
Please, fix for next release.
**Environment**

* React-admin version: 2.6.0

### PR DESCRIPTION
**Pull request by wmwart**
closes #2776

### CODE REVIEW

**Comment by fzaninotto** [comment]
There is a syntax error in your patch, which makes me suspect that you didn't even test it...

**Comment by fzaninotto** [comment]
bump, can you please fix your patch?

**Comment by wmwart** [comment]
fixed

**Comment by wmwart** [comment]
I'm new and I don't know what this is about. Please help me.

**Comment by djhi** [comment]
Sure :) We chose [prettier](https://prettier.io/) to automatically format the code in this project. It looks like you haven't configured your editor to apply it automatically. We planned for that and added commands you can run to fix the format.

At the project root, either:
- run `make prettier` if you can run make commands
- run `yarn prettier` if you can't run make commands

Then commit the result

**Comment by fzaninotto** [comment]
Not good, you  pushed changes about files you didn't modify.

**Comment by fzaninotto** [comment]
also, your checkout is probably not up to date with the master branch, please rebase

**Comment by fzaninotto** [comment]
Any updates?

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Pull request closed without merging**
