### PR TITLE
Add a custom filter property in useList

### PR DESCRIPTION
**Pull request by oguhpereira**
I tried to make the adjustment to be able to meet this feature #7970

Any suggestion or consideration for making a change just let me know!

### Requirements
- Allow a callback to perform filters on the view ✅ 
- Test ✅ 
- Docs ✅

### CODE REVIEW

**Comment by WiXSL** [comment]
This looks great!
We would like if you could change the name of the method from `setCustomFilter` to `setFilterCallback`

**Review by WiXSL — CHANGES_REQUESTED** [review]
This looks great!
We would like if you could change the name of the method from `setCustomFilter` to `filterCallback`
Other than that, it seems ok

**Comment by oguhpereira** [comment]
Adjusted according to comment https://github.com/marmelab/react-admin/pull/8116#pullrequestreview-1090238606

Commit https://github.com/marmelab/react-admin/pull/8116/commits/ce1535291fe377e9d39b9a18b543de8767e27fd0

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
