### PR TITLE
[RFR] Prevent submit on enter when submitOnEnter is false

### LINKED ISSUE #1797: submitOnEnter not working
```submitOnEnter={false}``` does not work, form submits anyway.

**What you were expecting:**
Form not to submit.

**What happened instead:**
Form submits - acts like html form with ```method="get"``` - copies form parameter to url query for some reason.

**Steps to reproduce:**
create very standard component as in related code below

**Related code:**
```
export const UserEdit = (props) => (
    <Edit {...props}>
        <SimpleForm submitOnEnter={false}>
            <TextInput source="userName"/>
        </SimpleForm>
    </Edit>
);
```

**Other information:**

**Environment**

* React-admin version: v2.0.0-RC2
* Last version that did not exhibit the issue (if applicable): didn't checked
* React version: 16.3.2
* Browser: Chrome 66
* Stack trace (in case of a JS error): none

### PR DESCRIPTION
**Pull request by djhi**
Fixes #1797

### CODE REVIEW

**Comment by fzaninotto** [comment]
I'm surprised that we need to do that, especially according to https://github.com/erikras/redux-form/issues/572#issuecomment-268905929...

Are you positive that it's the right way?

**Comment by djhi** [comment]
No I'm not and I just saw a bad side effect: enter does not work in `LongTextInput` anymore... However, there something not quite right with the solution from the comment you mention: we want to set the `onSubmit` prop on our form to allow remote submit and because that's the way a form should be used. I'll try something else

**Comment by djhi** [comment]
Ok, I found a better way. Unfortunately, it requires the changes from #1996

**Comment by djhi** [comment]
Summary:

```jsx
// in SimpleForm

handleSubmit = event => {
    const { handleSubmit, redirect, save, submitOnEnter } = this.props;
    if (!submitOnEnter && event.key === 'Enter') {
        event.preventDefault();
    }
    handleSubmit(values => save(values, redirect))(event);
};

// in render...
<form
    className={classnames('simple-form', className)}
    onSubmit={this.handleSubmit}
    {...sanitizeRestProps(rest)}
>
```

**Comment by djhi** [comment]
Included in #1996

**Pull request closed without merging**
