### PR TITLE
searchText  can never be undefined

### PR DESCRIPTION
**Pull request by daumann**

### CODE REVIEW

**Comment by fzaninotto** [comment]
Can you explain me what problem this change fixes?

**Comment by daumann** [comment]
Sorry for not replying earlier.
I encountered the problem when having _AutocompleteInput_ in a _Create_ form. Once you submit the form, this.state.searchText becomes _undefined_ and AutocompleteInput errors.

**Comment by fzaninotto** [comment]
I can't reproduce the error you describe in the simple demo on `master` and `next` branches. 

Can you provide a sandbox to reproduce the error?

**Comment by fzaninotto** [comment]
Bump

**Pull request closed without merging**
