### PR TITLE
[RFR] add allowsDuplicates prop and filter suggestions

### PR DESCRIPTION
**Pull request by Kunnu01**
Fixes: #2876 

ChipInput

### CODE REVIEW

**Comment by Kmaschta** [comment]
Is this issue still in WIP or can we review it?

**Comment by Kunnu01** [comment]
> Is this issue still in WIP or can we review it?

**Comment by Kunnu01** [comment]
> Is this issue still in WIP or can we review it?

Yes, now it is.

**Comment by Kunnu01** [comment]
I tried, but it doesn't work. Even if I directly pass it to `ChipInput`.

options
inputs

**Pull request closed without merging**
