### PR TITLE
[RFR] Migrate e2e tests to cypress

### PR DESCRIPTION
**Pull request by djhi**
- [x] Migrate tests
- [x] Cleanup
- [x] Document test commands
- [x] Find a better way to start the server before running the tests (probably custom script using cypress API: https://docs.cy)press.io/guides/guides/continuous-integration.html#Module-API)

### CODE REVIEW

**Comment by djhi** [comment]
> I find the cypress output too verbose

We might be able to finetune that by specifying a mocha reporter

**Comment by fzaninotto** [comment]
You're RFR but the checklist is still not complete...

**Comment by djhi** [comment]
Forgot to do it. Completed !

**Comment by fzaninotto** [comment]
If I understand correctly, you've remove the getters from the e2e Page objects. This worries me a bit, since it leads to plumbing in the e2e tests themselves, and a bit of code repetition. Can't you put the getters in the page objects with Cypress?

**Comment by djhi** [comment]
@fzaninotto 

> If I understand correctly, you've remove the getters from the e2e Page objects. This worries me a bit, since it leads to plumbing in the e2e tests themselves, and a bit of code repetition. Can't you put the getters in the page objects with Cypress?

Can you check the files inside the `cypress/integration` folder. It looks fine to me already.

**Comment by djhi** [comment]
I'll just make use of the `beforeEach` hook to avoid some code repetition

**Comment by djhi** [comment]
@fzaninotto Done!

**Comment by fzaninotto** [comment]
\o/

**Pull request merged**
