### PR TITLE
[RFR] Fix: automatic refresh

### PR DESCRIPTION
**Pull request by alinagaripova**
This functionality adds the ability to disable automatic page refresh

### CODE REVIEW

**Comment by fzaninotto** [comment]
Why would you want to do that?

**Comment by alinagaripova** [comment]
@fzaninotto to disable clearing of filled fields before saving

**Comment by fzaninotto** [comment]
Again, I don't see the bug. Version 3.8.2 fixed an issue here (see #5152) so this shouldn't be a problem anymore. 

Please explain in more details the use case, and add a unit test to your PR to show the bug prior to fixing it.

**Comment by alinagaripova** [comment]
Ok, thanks.
 I will try to update the version and solve the problem based on new fixes

**Pull request closed without merging**
