### PR TITLE
fix(resourcesRoutes): Added prop exact to all resources routes

### LINKED ISSUE #2910: [Bug] resourcesRoutes list is sensitive to ordering
We have the following `resourcesRoutes`:

```jsx
    <Resource
      name="project-management/projects"
      list={ProjectList}
      edit={ProjectEdit}
      create={ProjectCreate}
      show={ProjectShow}
    />,
    <Resource
      name="project-management/projects/services"
      list={ProjectServiceList}
      edit={ProjectServiceEdit}
      create={ProjectServiceCreate}
      show={ProjectServiceShow}
    />,
```

This fail to generate a working `<Route />`, because `project-management/projects/services` will catch before `project-management/projects`.

Instead we must order it DESC :  

```jsx
    <Resource
      name="project-management/projects/services"
      list={ProjectServiceList}
      edit={ProjectServiceEdit}
      create={ProjectServiceCreate}
      show={ProjectServiceShow}
    />,
    <Resource
      name="project-management/projects"
      list={ProjectList}
      edit={ProjectEdit}
      create={ProjectCreate}
      show={ProjectShow}
    />,
```

This will make a valid `<Route />`.

It can also be solved using `exact` props, and `customRoutes`, but this is too sensitive for being an expected behaviour, and it is not specified anywhere in the documentation.

If you agree, this ticket consists of taking all the user props from `<Resource />` and pass them to the `<Route />` component.

https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/Resource.tsx#L80

### PR DESCRIPTION
**Pull request by kopax**
Fix #3021  
Fix #2910

### CODE REVIEW

**Comment by Kmaschta** [comment]
Well, well! E2E tests are failing, especially on with custom pages.

**Comment by kopax** [comment]
Ok, I have no clue yet, I'll have a look now

**Comment by kopax** [comment]
@djhi I have investigated and I found out the fix your recommended was not actually the right one.
Adding `exact` here will create a `<Route path={`/${child.props.name}`} />`

image

What we want is to set the `exact` props to the 4 crud route, not just this one. I offer to restore the 1st fix.

**Comment by fzaninotto** [comment]
As seen in #2910, we won't address that issue.

**Pull request closed without merging**
