### PR TITLE
feat(layout): added layout

### PR DESCRIPTION
**Pull request by kopax**
And deprecated `appLayout`

Fix https://github.com/marmelab/react-admin/issues/2918

### CODE REVIEW

**Comment by fzaninotto** [comment]
Awesome! However, this should land in `next` rather than `master`, as it's a new feature. `master` is only for bug fixes.

**Comment by kopax** [comment]
> Bugfix PRs that don't break BC should be made against master. All other PRs (new features, bugfix with BC break) should be made against next.

Nice to know, I've missed that part sorry.

 I'll try to redo when IDEs will be disposed for this.

**Comment by fzaninotto** [comment]
Would you mind rebasing on `next`?

**Comment by kopax** [comment]
I have tried and it was a mess. Not sure if I did it correctly? Perhaps you could explain how to or I can give you the perms to the branch so you can perform the rebase from your own?

**Comment by fzaninotto** [comment]
Thanks!

**Comment by kopax** [comment]
Sorry about this, I will be careful next time.  Would love to know the trick with the rebase, I saw massive change between `next` and `master` and wasn't sure what to do to save the work.

**Comment by fzaninotto** [comment]
I merged the changes from master to next, so the rebase became much easier. I just changed the base branch in GitHub ;)

**Pull request merged**
