### PR TITLE
Optimize subscribe and publish function of memeryStore and localStora…

### PR DESCRIPTION
**Pull request by HEKEH**
Currently, `subscriptions` in `localStorageStore` and `memoryStore` is a two-level object while is a little confusing, and need to traverse each callback element to compare with `key` when use `publish`. 
This PR changes `subscriptions` into a single-level object, and relevant callbacks can be found directly by a key. This makes the code easier to understand, and performance is also a little improved.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Thanks! Can you provide before/after performance benchmarks?

**Comment by HEKEH** [comment]
> Thanks! Can you provide before/after performance benchmarks?

Not test it yet, but the previous `publish` function has to traverse every element to find some elements matched with the `key`, but the function modified does not need to, it can find the target callbacks directly, so the performance is a little improved.

**Comment by HEKEH** [comment]
> Thanks! Can you provide before/after performance benchmarks?

Not test it yet, but the previous `publish` function has to traverse every element to find some elements matched with the `key`, but the function modified does not need to, it can find the target callbacks directly, so the performance is a little improved.

**Comment by HEKEH** [comment]
> Thanks! Can you provide before/after performance benchmarks?
The main reason of this modification is that I feel using random number as key is a little weird, and I think it's not really needed. The performance improvement is not the key point.

**Comment by fzaninotto** [comment]
The tests don't pass in your PR, it doesn't "fix" anything, and it hasn't moved in three month. So I'm going to close it. 

If it's not broken, don't fix it™!

**Pull request closed without merging**
