### PR TITLE
Fix scrollbar not appear on scrollable tabs

### LINKED ISSUE #1689: A lot of tabs shows scrollbar and crashes the application
Example app: https://pp0o4x40p0.codesandbox.io/#/posts/13

I just copied the last tab a couple of times and you'll see a scrollbar at the bottom.
What I expected: that the `Tabs` component would be scrollable and the application not to crash. 
I think this is because the Tabs parent width is implicit instead of explicit.

### PR DESCRIPTION
**Pull request by AnkitaGupta111**
Closes #1689

### CODE REVIEW

**Comment by fzaninotto** [comment]
I don't see what your PR changes or fixes. Can you elaborate?

**Comment by fzaninotto** [comment]
Also, you're setting a div width to 0 while it should obviously not have zero width. Can you explain why you're doing that?

**Comment by AnkitaGupta111** [comment]
https://github.com/marmelab/react-admin/issues/1689#issuecomment-464111309
i just tried using this solution and now tabs are scrollable

**Comment by fzaninotto** [comment]
Blindly adding code without understanding how it works won't make a good fix. Please elaborate on the reason why we need this counter-intuitive null width.

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Pull request closed without merging**
