### PR TITLE
Fix linter warnings

### PR DESCRIPTION
**Pull request by fzaninotto**
See existing warnings: https://github.com/marmelab/react-admin/pull/8970/files

### CODE REVIEW

**Review by slax57 — CHANGES_REQUESTED** [review]
There are still other unchanged files with linter warnings (see https://github.com/marmelab/react-admin/pull/8978/files). Why not fix them in the same PR?

**Comment by fzaninotto** [comment]
I just hadn't seen them in previous builds... They should now be fixed.

**Comment by fzaninotto** [comment]
Due to an update in one of our rules, there are TONS of linter warnings. This PR reduces them to 153, down from 503 on `master`. I won't have time to remove more warnings today.

**Review by slax57 — APPROVED** [review]
Alright let's merge this set of fixes already :slightly_smiling_face:

**Pull request merged**
