### PR TITLE
Fix no-code-demo with correct config

### LINKED ISSUE #6432: [Lab] no-code example cannot start in codesandbox
Hi, It was nice there are new packages to make a try. 🚀

However when I run the no-code example in codesandbox, it is always showing a white screen.
I am not sure if there are some config files not set up correctly

**What you were expecting:**

The demo should run successfully

**What happened instead:**

The demo cannot start

**Steps to reproduce:**

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/no-code

**Related code:**

**Environment**

* React-admin version: 3.17
* Last version that did not exhibit the issue (if applicable): N/A
* React version: 17.0.2
* Browser: Edge 91
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by smeng9**
Closes #6432 

Here is an example codesandbox project with the changed config file that is working:
https://codesandbox.io/s/affectionate-allen-0xqij?file=/vite.config.ts:0-187

### CODE REVIEW

**Review by djhi — CHANGES_REQUESTED** [review]
Thanks! However, this change would make local development cumbersome. It would be nice to [detect we are on codesandbox](https://codesandbox.io/docs/environment#client-environments) and avoid aliases only in this case

**Comment by smeng9** [comment]
Hi @djhi, with environment variable detection it works as expected. Thanks.

https://codesandbox.io/s/github/smeng9/react-admin/tree/no-code-demo-fix/examples/no-code?file=/vite.config.ts

**Review by WiXSL — APPROVED** [review]

**Review by djhi — APPROVED** [review]
Thanks!

**Comment by WiXSL** [comment]
@djhi, you forgot to add it to the Milestone

**Pull request merged**
