### PR TITLE
Removed the button property from TreeNode

### LINKED ISSUE #3062: In Tree-component, every node adds a nested Ripple-effect on hover which kills performance
**What you were expecting:**

In ra-tree-ui-materialui, nested nodes don't create additional ripple effects

**What happened instead:**

Every nested nodes gets darker and creates an additional ripple effects which uses a lot of performance

**Steps to reproduce:**

Create a nested tree with ra-tree-ui-materialui and expand it. hover over one entry

**Related code:**

-

**Other information:**

the problem is visible even on the screencast: https://github.com/marmelab/react-admin/tree/4cf148571b9ec80493bca6979b2825ab2dd5e603/packages/ra-tree-ui-materialui 

**Environment**

* React-admin version: ^2.8.3
* Last version that did not exhibit the issue (if applicable): -
* React version: 16.8.*
* Browser: chrome
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by hacktisch**
To increase the performance

Fixes #3062

### CODE REVIEW

**Comment by macrozone** [comment]
@hacktisch  i tried that out, but it does not make any difference. Or am i doing it wrong?

**Comment by Kmaschta** [comment]
Thanks!
Can this change have other impact than just remove the overlay?

**Comment by djhi** [comment]
Please note that we are completely rewriting ra-tree for 3.0

**Comment by hacktisch** [comment]
> Thanks!
> Can this change have other impact than just remove the overlay?

I have to admit I cannot guarantee this, since this is the first and only part of the source code that I changed and all seems to be working well for me (it only removed the click animation on the button and all it's parents, but the click action remained to work) but I haven't tested in combination with all the other packages for instance. I would propose a better solution is to keep some sort of click animation, but prevent it from bubbling up to the parent nodes. But I didn't find how this could be done.

Is there any ETA for this rewrite of ra-tree?

**Comment by djhi** [comment]
> I would propose a better solution is to keep some sort of click animation, but prevent it from bubbling up to the parent nodes. But I didn't find how this could be done.

By checking `node.childre.length` ?

> Is there any ETA for this rewrite of ra-tree?

Not yet but I'll notify you here when we'll have a RC to test :)

**Comment by fzaninotto** [comment]
#3379 supersedes this PR, so I'm closing it. As @djhi said, we're rewriting the component with another approach that should improve the performance drastically.

**Pull request closed without merging**
