### PR TITLE
Fix select all over multiple pages

### LINKED ISSUE #6943: SelectAll works only in 1st page and doesn't work in other pages
I am using the custom grid as per the react-admin documentation. With the latest version of react-admin looks like the SelectAll is broken. 

I am encountering an issue : 

TypeError: Cannot read property 'selectable' of undefined
isRowSelectable

Here is how my code looks like : 
`
const MyDatagridBody = props => <DatagridBody {...props} row={<MyDatagridRow />} />;
const MyDatagrid = props => <Datagrid {...props} body={<MyDatagridBody />} />;

<MyDatagrid isRowSelectable={record => record.selectable}>
  <TextField source="status" label="Status" />
  ....
</MyDatagrid>
`
Stack trace 
`Uncaught TypeError: Cannot read property 'selectable' of undefined
    at isRowSelectable (Test.js:689)
    at DatagridHeader.js:33
    at Array.filter (<anonymous>)
    at DatagridHeader.js:32
    at handleInputChange (SwitchBase.js:96)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306)
    at executeDispatch (react-dom.development.js:389)
    at executeDispatchesInOrder (react-dom.development.js:414)
    at executeDispatchesAndRelease (react-dom.development.js:3278)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3287)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (react-dom.development.js:3257)
    at runEventsInBatch (react-dom.development.js:3304)
    at runExtractedPluginEventsInBatch (react-dom.development.js:3514)
    at handleTopLevel (react-dom.development.js:3558)
    at batchedEventUpdates$1 (react-dom.development.js:21871)
    at batchedEventUpdates (react-dom.development.js:795)
    at dispatchEventForLegacyPluginEventSystem (react-dom.development.js:3568)
    at attemptToDispatchEvent (react-dom.development.js:4267)
    at dispatchEvent (react-dom.development.js:4189)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at discreteUpdates$1 (react-dom.development.js:21887)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
`

### PR DESCRIPTION
**Pull request by WiXSL**
Fixes #6943

### CODE REVIEW

**Comment by basukb** [comment]
@WiXSL the fix looks good . [https://react-admin-git-fix-selectall-marmelab.vercel.app ](url) is working now

**Review by basukb — APPROVED** [review]
Looks good . Tested in [https://react-admin-git-fix-selectall-marmelab.vercel.app](url)

**Review by fzaninotto — CHANGES_REQUESTED** [review]
This solves the problem, but I think the code isn't clear. Why should a row be selected if there is no data? 

Take a look at the refactoring I made to the same file in `next` for a better version of the fix.

https://github.com/marmelab/react-admin/blob/ce3dceb212cc46d3cecb532ae11bb2a007afee0a/packages/ra-ui-materialui/src/list/datagrid/DatagridHeader.tsx#L61-L77

**Review by fzaninotto — APPROVED** [review]

**Comment by basukb** [comment]
May I know when this fix will be released ?

**Comment by WiXSL** [comment]
Is set in the next [milestone](https://github.com/marmelab/react-admin/milestone/175)
Should be pretty soon

**Pull request merged**
