### PR TITLE
Preserve extra query parameters in List view

### PR DESCRIPTION
**Pull request by Nilegfx**
## Problem

addressing https://github.com/marmelab/react-admin/issues/9932

## Solution
remove unnecessary query param sanitisation to keep any custom params in the url.

## How To Test

run `make test`

## Additional Checks

- [x] The PR targets `master` for a bugfix, or `next` for a feature
- [x] The PR includes **unit tests** (if not possible, describe why)
- [ ] The PR includes one or several **stories** (if not possible, describe why)
- [ ] The **documentation** is up to date

Also, please make sure to read the [contributing guidelines](https://github.com/marmelab/react-admin#contributing).

### CODE REVIEW

**Comment by fzaninotto** [comment]
Also, I consider this a new feature, so please target the `next` branch for this PR.

**Comment by Nilegfx** [comment]
@fzaninotto thanks for the review. 

I added the unit test. 

may I ask to treat this as a bug fix please🙏🏻, because it is hard for me to migrate my app to RA 5 now. I already have plans to migrate to RA 5 once it become the official release but migrating now especially without the official docs using V5 I am afraid my colleagues (whom most of them are backend engineers) will be a bit confused.

I can also open another PR for this to be treated as a feature and merge it to `next` branch if this will help you.

**Comment by Nilegfx** [comment]
you know what, you can treat it as a feature. I may use this to speed up the migration to v5 and we became early adopter.

**Comment by Nilegfx** [comment]
@fzaninotto please let me know if anything further from my side missing.

**Review by slax57 — APPROVED** [review]
Thanks!

**Pull request merged**
