### PR TITLE
fix(useSuggestions): fix suggestionText empty

### PR DESCRIPTION
**Pull request by binggg**
Fix TypeError: Cannot read property 'match' of undefined

### CODE REVIEW

**Comment by dhstack** [comment]
I am having this issue too in `react-admin 3.5.3`.

```
<ReferenceInput
    label="User"
    source="user.id"
    reference="users"
    sort={{ field: 'email', order: 'ASC' }}
>
  <AutocompleteInput optionText="email" validate={required()} />
</ReferenceInput>
```

As a workaround, one can use a `SelectInput` instead of an `AutocompleteInput`.

**Comment by fzaninotto** [comment]
Please fix the formatting as seen in the CI report.

**Comment by Luwangel** [comment]
@binggg Hi Booker Zhao, can you run prettier on PR so that we can merge it soon?

```
/home/travis/build/marmelab/react-admin/packages/ra-core/src/form/useSuggestions.ts
  116:28  error  Insert `⏎·············`                             prettier/prettier
  117:1   error  Replace `··············` with `··················`  prettier/prettier
  118:1   error  Insert `····`                                       prettier/prettier
  119:1   error  Replace `··············` with `··················`  prettier/prettier
  120:1   error  Insert `····`                                       prettier/prettier
```

**Comment by fzaninotto** [comment]
Superseded by #5125

**Pull request closed without merging**
