### PR TITLE
fix(dependencies): moved redux, react-redux and react-router-redux to peerDependencies.

### PR DESCRIPTION
**Pull request by kopax**
HI @fzaninotto. Sorry for the delay, we have not received a notification when you reopened #1683.

I have seen that you already moved part of the `dependencies` into `peerDependencies`.

**redux** should also be in `peerDependencies`, so does **react-redux**. 

I am not sure for `react-router-redux`, does this package use a store reference or does it just export a reducer to be used somewhere? 

By doubt and because it would solve all problems, I also added it as a `peerDependencies`.

### CODE REVIEW

**Comment by Kmaschta** [comment]
Isn't this change a breaking one?

**Comment by kopax** [comment]
@Kmaschta you are absolutely right, I forgot to mention it, you should add a not for people.

Moving a `dependencies` into `peerDependences` **and** `dependencies` will change nothing in development (you must have it at some point). In production, it will require the user to have our list of `peerDependencies` installed in it's `dependencies` or `devDependencies`.

If the user does not have `redux` in it's `devDependencies` or `dependencies`, then it will break.

If the user have `redux` or at least two sub depencencies that depend on `redux`, then it will work.

**Comment by fzaninotto** [comment]
Thanks! 

This really is a breaking change, so we won't merge it before 3.0. And we're waiting for react 16.8 and material-ui 4.0 to break BC for good, so this PR won't be merged before a few months at least.

**Comment by kopax** [comment]
Sure. About `react-router-redux`, the version `5.0.0-alpha.9` was never released. Instead they renamed the package `connected-router`.

I can't find the source code of `5.0.0-alpha.9`, but https://github.com/supasate/connected-react-router/blob/master/src/reducer.js show they are doing the reducer in here. It should also be a `peerDependencies`. 

Could we, at the same time. replace `react-router-redux@5.0.0-alpha.9` with `connected-router` (work the same way, just the import and the dependency change). 

At the same time, we could also update `redux`, `react-redux`, `react-router-dom`, `react-router`.

I've already played with all these versions and none of theme are breaking changes.

**Comment by fzaninotto** [comment]
see #1999 for react-router-redux

**Pull request closed without merging**
