### PR TITLE
[Demo] Improve CRM Demo Kanban code

### PR DESCRIPTION
**Pull request by slax57**
- [x] Improve code readability by removing useless variables and renaming
- [x] extract the update logic to dedicated functions
- [x] fix index computation logic for some corner cases (while persisting the changes)

Changes inspired by the work on https://github.com/marmelab/ra-example-kanban and the (upcoming) related blog post.

### CODE REVIEW

**Review by djhi — APPROVED** [review]
:+1:

**Comment by quentin-decre** [comment]
Great ! Thanks I will have a look.
Do you think PostColumn could use InfiniteList to render it's content ? Will all side-to-side infinite lists load next page when I scroll to the bottom of the body ?

**Comment by djhi** [comment]
> Great ! Thanks I will have a look. Do you think PostColumn could use InfiniteList to render it's content ? Will all side-to-side infinite lists load next page when I scroll to the bottom of the body ?

Probably tricky as each column has its own scroll container.

**Comment by quentin-decre** [comment]
:'(
How should we do that ?

**Comment by djhi** [comment]
I have no idea, yet. Could be a nice challenge for a hackday :)

**Pull request merged**
