### PR TITLE
Change Notification's error color from dark to main

### PR DESCRIPTION
**Pull request by WiXSL**
This is a left over from #5710

### CODE REVIEW

**Comment by fzaninotto** [comment]
Thanks!

**Comment by WiXSL** [comment]
This PR targets `next` branch but is listed in `3.11.2` milestone instead of `3.12`

**Comment by fzaninotto** [comment]
My mistake. Milestone updated.

**Comment by fzaninotto** [comment]
As explained in #5710, the result isn't good looking, so we need to discuss that further. In the meantime, and since we must deliver 3.12, I'll be reverting the PR.

**Pull request merged**
