### PR TITLE
chore(deps): Update linting tools

### PR DESCRIPTION
**Pull request by antdking**
Recently committed some code that Prettier doesn't understand.
Update everything while I'm changing Prettier (which is what caused the
whitespace changes anyway).

### CODE REVIEW

**Review by djhi — APPROVED** [review]
Thanks!

**Comment by WiXSL** [comment]
Tests are failing

**Comment by antdking** [comment]
> Tests are failing

Done. I'd included Jest in the upgrade too by mistake.

**Comment by fzaninotto** [comment]
This will force all currently open PRs to rebase. We should only merge it at the last moment, when the 4.0 scope is done.

**Comment by WiXSL** [comment]
Needs rebase

**Comment by djhi** [comment]
We forgot about this one. Let's eventually do another in v5. Thanks anyway!

**Pull request closed without merging**
