### PR TITLE
[WIP] convert ra-ui components to classes/useStyles

### PR DESCRIPTION
**Pull request by MohammedFaragallah**
refs #3453

### CODE REVIEW

**Comment by Kunnu01** [comment]
@MohammedFaragallah Do you need any sort of help in converting the components?

**Comment by MohammedFaragallah** [comment]
Sure thank you @Kunnu01 i did the conversions for this PR now i'm trying to pass cypress tests if you can give it a look would be great, any notes would be very helpful actually it's my first opensource contribution.

**Comment by fzaninotto** [comment]
Since this PR isn't ready, we had to merge other PRs that already do part of the migration to useStyles. So this PR now needs rebase. If can't solve the problem with the unit tests soon, I believe we won't be able to merge it at all, as we'll continue migrating components little by little as we work on inputs, fields, etc. 

I suggest you split this PR into smaller ones, targeting a directory of components, and focusing on making the tests pass.

**Comment by fzaninotto** [comment]
Just like for #3461, please split this PR into smaller ones and make sure the tests always pass. Thanks for your work!

**Pull request closed without merging**
