### PR TITLE
Added rowStyle to SimpleList rebased

### PR DESCRIPTION
**Pull request by ValentinnDimitroff**
#5252

### CODE REVIEW

**Comment by WiXSL** [comment]
@ValentinnDimitroff could you rebase again?

**Comment by fzaninotto** [comment]
I'm not sure why this PR got closed. Maybe I did a bad rebase or something. Apologies for the unintended rudeness.

I can't reopen it, would you mind opening a new one?

**Comment by ValentinnDimitroff** [comment]
Sure, no worries - it happens :)

**Comment by ValentinnDimitroff** [comment]
No worries, it happens but I also can't open the PR against the next branch cause it says the commits are already merged. Which is actually correct as I can see changes both on `master `and `next `branches.

Text me if I can or should do something else.

**Comment by ValentinnDimitroff** [comment]
Ok, now I found out what happened - This is my duplicated PR of the actual one which is already merged - #5252. 

So we are all good I think.

**Pull request closed without merging**
