### PR TITLE
Firestore Data Provider

### PR DESCRIPTION
**Pull request by rafalzawadzki**
Added a third-party repository supporting the Firestore database.

### CODE REVIEW

**Comment by fzaninotto** [comment]
There is already a third-party Firebase provider, what's different in this one? Why didn't you contribute these differences to the original library?

**Comment by rafalzawadzki** [comment]
Hello @fzaninotto, the existing Firebase provider supports only Realtime Database and not its successor, Cloud Firestore. There are major differences in data structure, querying, SDKs etc between these two and it does not make sense to build one provider to cater to both of them.

**Comment by fzaninotto** [comment]
Then please update the first link to point to https://firebase.google.com/docs/firestore/ rather than to your plugin repository

**Comment by rafalzawadzki** [comment]
Committed changes of both Firebase & Firestore doc links for clarity 👍

**Comment by fzaninotto** [comment]
Great, thanks!

**Pull request merged**
