### PR TITLE
Fix warning on catchall page due to improper sanitization in <NotFound> component.

### PR DESCRIPTION
**Pull request by WiXSL**
This could happend from `RoutesWithLayout.tsx`.
```jsx
...
<Route
    render={routeProps =>
        createElement(catchAll, {
            ...routeProps,
            title,
        })
    }
 />
...

### CODE REVIEW

**Comment by fzaninotto** [comment]
No, I don't think we should do that. If a route is to be used as a child of Route, it should expect these props to be passed.

**Comment by Luwangel** [comment]
Hi, thanks for your contribution :)

By reading your PR, I'm wondering what issue you try to fix. I think it's the warning on the NotFound page, but you didn't mention it in the description. Could you write what you try to achieve?

In addition, you suggest another change which could be a good improvement.  Why didn't you do it?

Regards,
Adrien

**Comment by WiXSL** [comment]
I tried to avoid they staticContext error thrown on NotFound component render.
They comment was to show the origin of the problem.

**Comment by WiXSL** [comment]
@fzaninotto, In this  case the `sanitizeRestProps` is called only to sanitize props to be applied to a `div` element inside `NotFound` component.


```jsx
const NotFound = ({ className, classes: classesOverride, title, ...rest }) => {
    const classes = useStyles({ classes: classesOverride });
    const translate = useTranslate();
    useAuthenticated();
    return (
        <div
            className={classnames(classes.container, className)}
            {...sanitizeRestProps(rest)}
        >
    //...

**Comment by fzaninotto** [comment]
Sorry, I read too fast. Reopening.

**Comment by fzaninotto** [comment]
In the future, can you please post a more precise description of the bug you're trying to fix? Otherwise we have to guess and sometimes we guess wrong ;)

**Comment by WiXSL** [comment]
No problem, It was my fault, , I assume it was a trivial change to understand.

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
