### PR TITLE
Add Footer

### PR DESCRIPTION
**Pull request by BartoGabriel**
The footer component is added to use in the layout, and a small documentation is added.

imagen

### CODE REVIEW

**Comment by djhi** [comment]
Do you mind adding a screenshot in your PR description ?

**Comment by BartoGabriel** [comment]
The image example was taken applying styles, to appreciate the position of the footer.

**Comment by BartoGabriel** [comment]
@djhi It depends. For example, look at this theme:
https://demos.creative-tim.com/material-dashboard-pro-react/?_ga=2.122576203.1918928358.1544536166-1806264706.1543430526#/dashboard

**Comment by BartoGabriel** [comment]
Our tests applying styles in react admin:

imagen

**Comment by BartoGabriel** [comment]
@fzaninotto  I agree with you, maybe it should not be part of the core. I hope that at least, this PR will serve a user who wants to implement something similar.

**Pull request closed without merging**
