### PR TITLE
Fix RichTextInput paragraph margin bottom.

### PR DESCRIPTION
**Pull request by WiXSL**
ra

### CODE REVIEW

**Comment by fzaninotto** [comment]
I don' understand the problem. It's normal that paragraphs have a bottom margin.

**Comment by WiXSL** [comment]
But in a TextArea like component we should be able to have each line sticked together as we type enter key.

**Comment by fzaninotto** [comment]
It's not a textarea, it's a rich text editor. The text should look as much as possible as the rendered text, in which paragraphs have margins.

**Comment by WiXSL** [comment]
All right I'll have to override the style locally.

**Pull request closed without merging**
