### PR TITLE
change SET_SORT reducer to accept a order value.

### PR DESCRIPTION
**Pull request by frankPairs**
new PR related to https://github.com/marmelab/react-admin/pull/2855

### CODE REVIEW

**Comment by fzaninotto** [comment]
This will be a pain to rebase because the files you've modified in `next` were migrated to TypeScript on `master`. So I'll wait until we rebase `next` on `master` and ask you to rebase your PR then.

**Comment by frankPairs** [comment]
@fzaninotto ok, sounds good.

**Comment by djhi** [comment]
The TypeScript migration has been merged into next too. Would you mind rebasing? Thanks!

**Comment by frankPairs** [comment]
ok @djhi , during the next weeks I will update this PR.

Thanks!

**Comment by frankPairs** [comment]
@djhi updated!

**Comment by djhi** [comment]
Thanks!

**Pull request merged**
