### PR TITLE
Add ability to customize the notification element in the Login page

### PR DESCRIPTION
**Pull request by hieusmiths**
We can't custom notification, so i decided to make this PR.

### CODE REVIEW

**Review by djhi — APPROVED** [review]
Good catch, thanks!

**Comment by hieusmiths** [comment]
> Good catch, thanks!

:100:

**Comment by fzaninotto** [comment]
Hi, and thanks for your PR! 

This is technically a new feature, so you should PR against the `next` branch rather than `master`.

**Comment by hieusmiths** [comment]
> Hi, and thanks for your PR!
> 
> This is technically a new feature, so you should PR against the `next` branch rather than `master`.

Changed to next branch

**Review by fzaninotto — APPROVED** [review]

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
