### PR TITLE
Update Unit Testing documentation

### PR DESCRIPTION
**Pull request by mexitalian**
The previous import location threw an error for me as it couldn't be found.

### CODE REVIEW

**Comment by djhi** [comment]
The `react-admin` package just re-export what `ra-core` exports. So both imports should work

**Comment by Kmaschta** [comment]
I somewhat agree with that PR: `ra-core` isn't documented (yet) and it might be confusing to the early adopters why we require that package in a simple unit test example.

**Comment by djhi** [comment]
@fzaninotto What do you think about it? I agree with @Kmaschta

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
