### PR TITLE
fixed AutocompleteInput popup to re-render after choice is selected

### PR DESCRIPTION
**Pull request by FACOLOMBANI**
Hi,

This is a PR to fix AutocompleteInput issue #2428. I added the prop focusInputOnSuggestionClick by default to false, and since the input loses focus on suggestion selection, i had to change the state when calling handleSuggestionSelected().

Best Regards.

### CODE REVIEW

**Comment by fzaninotto** [comment]
You seem to use different prettier settings than us. Can you please avoid reformatting on save or use our prettier preset, to minimize the coding style changes?

**Comment by FACOLOMBANI** [comment]
Of course, i apologize, just ran your prettier settings.

**Comment by fzaninotto** [comment]
You patch doesn't work. I tested on the simple example, in a Comment detail, changing the related post doesn't work anymore.

**Comment by FACOLOMBANI** [comment]
This is weird, i tested it locally on the reviews component using the customer filter and it worked fine, i'll check it again

**Comment by FACOLOMBANI** [comment]
I added a new case in the handleChange function, can you please retest with this modification?

**Comment by djhi** [comment]
Thanks!

**Pull request merged**
