### PR TITLE
[RFR] Add 6 new data providers to the Ecosystem

### PR DESCRIPTION
**Pull request by fzaninotto**
* Django Rest Framework
* HAL
* JSON HAL
* REST-HAPI
* Sails.js
* Spring Boot

image

Not all of them are open-source, but they are all a good starting point.

Thanks npmjs.com for the list of dependent packages.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Back to WIP, I forgot some colons

**Comment by fzaninotto** [comment]
Back to RFR

**Comment by fzaninotto** [comment]
Back to WIP, I found another one!

**Comment by fzaninotto** [comment]
Nope, it's an existing one which has been renamed. Back to RFR.

**Comment by Kmaschta** [comment]
This PR has a frequency of WIP/RFR switch of more than 1Hz

**Pull request merged**
